import LocalizedStrings from 'react-native-localization';

export const strings = new LocalizedStrings({
  en: {
    'has already been applied and cannot be used in conjunction with other coupons.': 'has already been applied and cannot be used in conjunction with other coupons.',
    'Sorry, coupon': "Sorry, coupon",
    Retry: 'Retry',
    'View Product': 'View Product',
    'Selected for Comparison': 'Selected for Comparison',
    'Al Asimah': 'Al Asimah',
    'Abdullah Al-Salem': 'Abdullah Al-Salem',
    Adailiya: 'Adailiya',
    'Bneid Al Qar': 'Bneid Al Qar',
    Daiya: 'Daiya',
    Dasma: 'Dasma',
    Dasman: 'Dasman',
    Doha: 'Doha',
    Faiha: 'Faiha',
    Ghornata: 'Ghornata',
    'Jaber Al Ahmad': 'Jaber Al Ahmad',
    Kaifan: 'Kaifan',
    Khaldiya: 'Khaldiya',
    'Kuwait City': 'Kuwait City',
    Mansouriya: 'Mansouriya',
    Mirqab: 'Mirqab',
    'Mubarakiya Camps': 'Mubarakiya Camps',
    Nahda: 'Nahda',
    'North West Sulaibikhat': 'North West Sulaibikhat',
    Nuzha: 'Nuzha',
    Qadsiya: 'Qadsiya',
    Qibla: 'Qibla',
    Qortuba: 'Qortuba',
    Rawda: 'Rawda',
    Salhiya: 'Salhiya',
    Shamiya: 'Shamiya',
    Sharq: 'Sharq',
    coupon_cannot_be_applied:"Sorry, this coupon is not applicable to selected products. ",
    'Flat rate Far Area':'Flat rate Far Area',
    'Shuwaikh Administrative': 'Shuwaikh Administrative',
    'Shuwaikh Educational': 'Shuwaikh Educational',
    'Shuwaikh Industrial 1': 'Shuwaikh Industrial 1',
    'Shuwaikh Industrial 2': 'Shuwaikh Industrial 2',
    'Shuwaikh Industrial 3': 'Shuwaikh Industrial 3',
    'Shuwaikh Medical': 'Shuwaikh Medical',
    'Shuwaikh Residential': 'Shuwaikh Residential',
    Shuwaikh: 'Shuwaikh',
    Sulaibikhat: 'Sulaibikhat',
    Surra: 'Surra',
    Yarmouk: 'Yarmouk',
    Hawali: 'Hawali',
    'Al-Bedae': 'Al-Bedae',
    Bayan: 'Bayan',
    Hawally: 'Hawally',
    Hitteen: 'Hitteen',
    Jabriya: 'Jabriya',
    'Maidan Hawally': 'Maidan Hawally',
    'Ministries Zone': 'Ministries Zone',
    Mishrif: 'Mishrif',
    'Mubarak Al-Abdullah - West Mishref': 'Mubarak Al-Abdullah - West Mishref',
    Rumaithiya: 'Rumaithiya',
    Salam: 'Salam',
    Salmiya: 'Salmiya',
    Salwa: 'Salwa',
    Shaab: 'Shaab',
    Shuhada: 'Shuhada',
    Siddiq: 'Siddiq',
    Zahra: 'Zahra',
    'Al Farwaniyah': 'Al Farwaniyah',
    'Abdullah Al-Mubarak': 'Abdullah Al-Mubarak',
    Airport: 'Airport',
    Andalous: 'Andalous',
    'Ardhiya 4': 'Ardhiya 4',
    Ardhiya: 'Ardhiya',
    'Ardiya Small Industrial': 'Ardiya Small Industrial',
    'Ardiya Storage Zone': 'Ardiya Storage Zone',
    Ashbeliah: 'Ashbeliah',
    Dhajeej: 'Dhajeej',
    Farwaniya: 'Farwaniya',
    Ferdous: 'Ferdous',
    'Jeleeb Al-Shuyoukh': 'Jeleeb Al-Shuyoukh',
    Khaitan: 'Khaitan',
    Omariya: 'Omariya',
    Rabiya: 'Rabiya',
    Rai: 'Rai',
    Reggai: 'Reggai',
    Rehab: 'Rehab',
    'Sabah Al-Nasser': 'Sabah Al-Nasser',
    'Sheikh Saad Al Abdullah Airport': 'Sheikh Saad Al Abdullah Airport',
    'Mubarak Al-Kabeer': 'Mubarak Al-Kabeer',
    'Abu Ftaira': 'Abu Ftaira',
    'Abu Hasaniya': 'Abu Hasaniya',
    Adan: 'Adan',
    'Al Masayel': 'Al Masayel',
    'Al-Qurain': 'Al-Qurain',
    'Al-Qusour': 'Al-Qusour',
    Fnaitess: 'Fnaitess',
    Messila: 'Messila',
    'Mubarak Al-Kabir': 'Mubarak Al-Kabir',
    'Sabah Al-Salem': 'Sabah Al-Salem',
    'Sabhan Industrial': 'Sabhan Industrial',
    'South Wista': 'South Wista',
    'West Abu Fetera Small Indust': 'West Abu Fetera Small Indust',
    Wista: 'Wista',
    'Al Jahra': 'Al Jahra',
    'Al Naeem': 'Al Naeem',
    'Jahra Amgarah Industrial': 'Jahra Amgarah Industrial',
    'Jahra Area': 'Jahra Area',
    Kabd: 'Kabd',
    Alnasseem: 'Alnasseem',
    Aloyoun: 'Aloyoun',
    Alqasr: 'Alqasr',
    'Saad Al Abdullah': 'Saad Al Abdullah',
    'Alsulaibiya Industrial 1': 'Alsulaibiya Industrial 1',
    'Alsulaibiya Industrial 2': 'Alsulaibiya Industrial 2',
    Alsulaibiya: 'Alsulaibiya',
    Taima: 'Taima',
    Alwaha: 'Alwaha',
    Alqairawan: 'Alqairawan',
    'Al Ahmadi': 'Al Ahmadi',
    'Abu Halifa': 'Abu Halifa',
    'Al-Ahmadi': 'Al-Ahmadi',
    'Ali Sabah Al-Salem - Umm Al Hayman': 'Ali Sabah Al-Salem - Umm Al Hayman',
    'Al-Julaiaa': 'Al-Julaiaa',
    Bnaider: 'Bnaider',
    Dhaher: 'Dhaher',
    Egaila: 'Egaila',
    'Fahad Al Ahmed': 'Fahad Al Ahmed',
    Fahaheel: 'Fahaheel',
    Fintas: 'Fintas',
    Hadiya: 'Hadiya',
    'Jaber Al Ali': 'Jaber Al Ali',
    Khairan: 'Khairan',
    Magwa: 'Magwa',
    Mahboula: 'Mahboula',
    Mangaf: 'Mangaf',
    'Mina Abdullah': 'Mina Abdullah',
    Nuwaiseeb: 'Nuwaiseeb',
    Riqqa: 'Riqqa',
    'Sabah Al Ahmad Marine City': 'Sabah Al Ahmad Marine City',
    'Sabah AL Ahmad residential': 'Sabah AL Ahmad residential',
    Sabahiya: 'Sabahiya',
    'Shuaiba Port': 'Shuaiba Port',
    'South Sabahiya': 'South Sabahiya',
    'Wafra farms': 'Wafra farms',
    'Wafra residential': 'Wafra residential',
    Zour: 'Zour',
    'New Total: ': 'New Total: ',
    Delivery: 'Delivery',
    'Local pickup': 'Local Pickup',
    'E-Payment through Credit card and Debit card':
      'E-Payment through Credit card and Debit card',
    'Online Payment: Master Visa Card': 'Online Payment: Master Visa Card',
    'Online Payment: K-NET': 'Online Payment: K-NET',
    'Pay with cash upon delivery.': 'Pay with cash upon delivery.',
    'Grand Total': 'Grand Total',
    'Sub Total': 'Sub Total',
    Preferences: 'Preferences',
    'Following Items Not Available': 'Following Items Not Available',
    'Order Failed': 'Order Failed',
    'Free Shipping': 'Free Shipping',
    'Free shipping': 'Free Shipping',
    'Coupon Min Amount':
      'This Coupon Can be Applied Only If the Total Amount of Cart is Minimum: ',
    'Coupon Max Amount':
      'This Coupon Can be Applied Only If the Total Amount of Cart is Maximum: ',
    'Search Your Area': 'Search Your Area',
    'Select Area': 'Select Area',
    Yes: 'Yes',
    No: 'No',
    Sale: 'Sale',
    'Add to Cart': 'Add to Cart',
    'Return Policy': 'Return Policy',
    'Delivery Policy': 'Delivery Policy',
    'Top Rated Products': 'Top Rated Products',
    'Already Added in Wishlist': 'Already Added in Wishlist',
    'Product Removed From Wishlist': 'Product Removed From Wishlist',
    'Wishlist Emptied': 'Wishlist Emptied',
    'Failed to Join Waitlist': 'Failed to Join Waitlist',
    'Not Enough Stock Available': 'Not Enough Stock Available',
    'Product Quantity Cannot be Reduced': 'Product Quantity Cannot be Reduced',
    'Cart Emptied': 'Cart Emptied',
    'Product Removed From Cart': 'Product Removed From Cart',
    'No More Items': 'No More Items',
    'Invalid Password': 'Invalid Password',
    'Invalid Username': 'Invalid Username',
    'Set Language': 'Set Language',
    username: 'Username',
    first_name: 'First Name',
    last_name: 'Last Name',
    sku: 'Sku',
    short_description: 'Short Description',
    related_products:'Related Products',
    'Order Detail': 'Order Detail',
    Newsletter: 'Newsletter',
    'Subscribe to Newsletter': 'Subscribe to Newsletter',
    Confirmation: 'Confirmation',
    'Your Order Has Been Placed': 'We have received your order',
    'Your Order Is': 'Your order no. is',
    thanksForPurchase: `Thank You For Your Purchase\n\nYou will receive an order confirmation email with details of your order and a link to track its progress.`,
    'Continue Shopping': 'Continue Shopping',
    Building: 'Building',
    'Secure Checkout': 'Secure Checkout',
    Description: 'Description',
    description: 'Description',
    Reviews: 'Reviews',
    'Select Color': 'Select Color',
    'Additional Information': 'Additional Information',
    'Add Review': 'Add Review',
    'Select Size': 'Select Size',
    'Kuwait Online Shopping Store': 'Kuwait Online Shopping Store',
    'Shop Top Brand': 'Shop Top Brand',
    'Discount Code': 'Discount Code',
    'Chat on WhatsApp': 'Chat on WhatsApp',
    'Continue as Guest': 'Continue as Guest',
    'Featured Categories': 'Featured Categories',
    'Enter Name': 'Enter Name',
    'Continue Without Login': 'Continue Without Login',
    "Don't Have An Account?": "Don't Have An Account?",
    'Already Have An Account?': 'Already Have An Account?',
    'Or Login With': 'Or Login With',
    'Enter Password': 'Enter Password',
    'Customer Services': 'Customer Services',
    'Compare Products': 'Compare Products',
    Settings: 'Settings',
    'Website - Luma': 'Website - Luma',
    'Language - English': 'Language - English',
    'Currency - $ US Dollar': 'Currency - $ US Dollar',
    'Account Information': 'Account Information',
    'Address Book': 'Address Book',
    'Product Reviews': 'Product Reviews',
    'Downloadable Product': 'Downloadable Product',
    "What's New": "What's New",
    Popular: 'Popular',
    Featured: 'Featured',
    Women: 'Women',
    Men: 'Men',
    Kids: 'Kids',
    'See All': 'See All',
    'Search Your Product': 'Search Your Product',
    'Enter Your Email to Recieve Notification When Product Arrives':
      'Enter Your Email to Recieve Notification When Product Arrives',
    'Enter Valid Email': 'Enter Valid Email',
    'Join Waitlist': 'Join Waitlist',
    'Sold Out': 'Sold Out',
    'Invalid First Name': 'Invalid First Name',
    'Invalid Last Name': 'Invalid Last Name',
    'Invalid Company': 'Invalid Company',
    'Invalid Adress': 'Invalid Adress',
    'Invalid City': 'Invalid City',
    'Invalid State': 'Invalid State',
    'Invalid Postcode': 'Invalid Postcode',
    'Invalid Country': 'Invalid Country',
    'Invalid Email': 'Invalid Email',
    'Invalid Phone': 'Invalid Phone',
    'Invalid Street': 'Invalid Street',
    'Invalid Block': 'Invalid Block',
    'Invalid Email or Password':'Invalid Email or Password',
    Item_is_already_added_into_cart: 'Item is already added into cart',
    'You Cannot Use This Coupon': 'You Cannot Use This Coupon',
    'Coupon Usage Limit Exceeded': 'Coupon Usage Limit Exceeded',
    OK: 'OK',
    'Sort by default': 'Sort by: Default',
    'Sort by': 'Sort by',
    'Go Back': 'Go Back',
    'Failed to Login': 'Failed to Login',
    'Email cannot be empty': 'Email cannot be empty',
    'Password is Invalid': 'Password is Invalid',
    'Sort by Popularity': 'Sort by: Popularity',
    'Sort by Average Rating': 'Sort by: Average Rating',
    'Sort by Price Low': 'Sort by: Price Low',
    'Sort by Price High': 'Sort by: Price High',
    'Sort by Latest': 'Sort by: Latest',
    Popularity: 'Popularity',
    'Average Rating': 'Average Rating',
    'Price Low': 'Price Low',
    'Price High': 'Price High',
    Latest: 'Latest',
    'Total Price must be above 5 KD to checkout':
      'Total Price must be above 5 KD to checkout',
    'Hadafy Deals': 'Hadafy Deals',
    'No Items Found': 'No Items Found',
    'No Reviews Found': 'No Reviews Found',

    Cancel: 'Cancel',
    'Login to Post Review': 'Login to Post Review',
    'Failed to Add Review': 'Failed to Add Review',
    'Review Added Successfully': 'Review Added Successfully',
    'Not Logged In': 'Not Logged In',
    'Please share your opinion regarding this product.':
      'Please share your opinion regarding this product.',
    'Write Your Review': 'Write Your Review',
    'Rate This Product': 'Rate This Product',
    'Select Date': 'Select Date',
    SaleEnded: 'Sale Ended',
    'This Coupon Can Only be Applied Alone. All Other Coupons will be removed':
      'This Coupon Can be Applied Alone. All Other Coupons will be removed',
    Warning: 'Warning',
    'Coupon Expired': 'Coupon Expired',
    Code: 'Code',
    'Enter Coupon Code': 'Enter Coupon Code',
    Discount: 'Discount',
    Invalid_coupon: 'Invalid Coupon',
    'No Products found': 'No Products found',
    Coupon: 'Coupon',
    No_Coupon_Available: 'No Coupon Available',
    '3D Canvas': '3D Canvas',
    '4-Colored Pens': '4-Colored Pens',
    'A4 Envelops': 'A4 Envelops',
    'Acrylic & Gouache Paints': 'Acrylic & Gouache Paints',
    'Adhesives & Tapes': 'Adhesives & Tapes',
    'ALL Categories': 'ALL Categories',
    'Arts & Crafts': 'Arts & Crafts',
    'Ballpoint & Rollerball Pens': 'Ballpoint & Rollerball Pens',
    Binders: 'Binders',
    'Binders & Folders': 'Binders & Folders',
    'Board Markers & Erasers': 'Board Markers & Erasers',
    Books: 'Books',
    Brands: 'Brands',
    'Brushes & Palettes': 'Brushes & Palettes',
    Calculators: 'Calculators',
    'Canvas & Pads': 'Canvas & Pads',
    Chalk: 'Chalk',
    'Chalks & Charcoals': 'Chalks & Charcoals',
    'Children Books': 'Children Books',
    Clay: 'Clay',
    Cleaners: 'Cleaners',
    'Clips & Pins': 'Clips & Pins',
    'Coloring Books': 'Coloring Books',
    'Coloring Markers': 'Coloring Markers',
    'Coloring Pencils': 'Coloring Pencils',
    Correctors: 'Correctors',
    Crayons: 'Crayons',
    'Cut & Paste Books': 'Cut & Paste Books',
    Cutters: 'Cutters',
    'Dividers & Pockets': 'Dividers & Pockets',
    'Drawing & Coloring': 'Drawing & Coloring',
    'Drawing & Painting Pads': 'Drawing & Painting Pads',
    'Drawing Pens': 'Drawing Pens',
    Envelops: 'Envelops',
    'Erasers & Sharpeners': 'Erasers & Sharpeners',
    'Fineliner & Sign Pens': 'Fineliner & Sign Pens',
    'Flash Drives': 'Flash Drives',
    'Geometry Sets': 'Geometry Sets',
    'Glues & Adhesives': 'Glues & Adhesives',
    'Graphite & Mechanical Pencils': 'Graphite & Mechanical Pencils',
    Highlighters: 'Highlighters',
    'Learning & Education': 'Learning & Education',
    'Letter Envelops': 'Letter Envelops',
    Locks: 'Locks',
    'Looseleaf & Graph Paper': 'Looseleaf & Graph Paper',
    Markers: 'Markers',
    'Mediums & Varnishes': 'Mediums & Varnishes',
    'Notebooks & Memos': 'Notebooks & Memos',
    'Notebooks & Papers': 'Notebooks & Papers',
    'Office and Students Supplies': 'Office and Students Supplies',
    'Office Equipment': 'Office Equipment',
    'Other Office Equipment': 'Other Office Equipment',
    'Other Paints': 'Other Paints',
    Others: 'Others',
    'Page Markers & Flags': 'Page Markers & Flags',
    'Paint & Clay': 'Paint & Clay',
    PanPastels: 'PanPastels',
    'Parenting Books': 'Parenting Books',
    Pastels: 'Pastels',
    Pencils: 'Pencils',
    Pens: 'Pens',
    'Plastic Folders': 'Plastic Folders',
    'Plastic Rulers': 'Plastic Rulers',
    'Printing Papers': 'Printing Papers',
    Punchers: 'Punchers',
    Resin: 'Resin',
    'Resin Colors': 'Resin Colors',
    'Resin, Adhesives & Cleaners': 'Resin, Adhesives & Cleaners',
    Rulers: 'Rulers',
    'School Handbooks (Gr. 1-12)': 'School Handbooks (Gr. 1-12)',
    'School Packages': 'School Packages',
    Scissors: 'Scissors',
    'Scissors and Cutters': 'Scissors and Cutters',
    'Silicone Molds': 'Silicone Molds',
    Sketchbooks: 'Sketchbooks',
    'Sketching Pencils': 'Sketching Pencils',
    'Staplers and Staples': 'Staplers and Staples',
    'Steel Rulers': 'Steel Rulers',
    'Sticky Notes': 'Sticky Notes',
    'Stretched Canvas & Panels': 'Stretched Canvas & Panels',
    'Student Handbooks': 'Student Handbooks',
    'Tapes & Dispensers': 'Tapes & Dispensers',
    'Tie Dye': 'Tie Dye',
    'Transfer Papers': 'Transfer Papers',
    Uncategorized: 'Uncategorized',
    'Water Bottles': 'Water Bottles',
    'Watercolor & Oil Paints': 'Watercolor & Oil Paints',
    'Writing Pads': 'Writing Pads',
    Returns_and_Exchange: 'Returns and Exchange',
    bookingTerms: 'booking terms',
    And: 'And',
    I_agree_to_the: 'I agree to the',
    Dont_have_an_account: "Don't have an account?",
    Select_Gender: 'Select Gender',
    CreatePassword: 'Create a Password',
    Your_Username: 'Your Username',
    Male: 'Male',
    Female: 'Female',
    male: 'Male',
    female: 'Female',
    Other: 'Other',
    other: 'Other',
    Balance: 'Balance',
    Login: 'Login',
    'Password cannot be empty': 'Password cannot be empty',
    enter_emal_username: 'Enter Email address or Username',
    Add_to_cart: 'Add To Cart',
    No_Reviews: 'No Reviews',
    Add_Review: 'Add Review',
    Hadafy_Deals: 'Hadafy Deals',
    'Best Sellers': 'Best Sellers',
    Best_Sellers_Products: 'Best Sellers Products',
    Place_Order: 'Place Order',
    Apply_Coupon: 'Apply Coupon',
    Agree_terms_Conditions:
      'I have read and agree to the website Terms and Conditions',
    Your_Personal_data:
      'Your personal data will be used to process your order, support your experience throughout this website, and for other purposes Described in our',
    Visa_Master_Cards: 'Visa/Master Cards',
    Cash_on_Delivery: 'Cash on Delivery',
    Visa_MasterCard_1_5__fee: 'Visa/MasterCard 1.5% fee',
    My_Orders: 'My Orders',
    No_Area_Selected: 'No Area Selected',
    Order_Notes_Detail:
      'Notes about your order, e.g. special notes for delivery',
    Order_Notes_Optional_: 'Order Notes(Optional)',
    Bill_To_Different_Address: 'Bill To Different Address',
    Your_Phone: 'Your Phone',
    Avenue: 'Avenue',
    Block: 'Block',
    Your_Area: 'Your Area',
    Kuwait: 'Kuwait',
    Billing_Details: 'Billing Details',
    Error: 'Error',
    Please_select_a_Payment_Method: 'Please select a Payment Method',
    View_More: 'View More',
    Items: 'Items',
    Quantity: 'Quantity',
    Your_Country: 'Your_Country',
    Your_Postcode: 'Your Postcode',
    Your_State: 'Your State',
    Your_City: 'Your_City',
    Address_Line_1: 'Address Line 1',
    Address_Line_2: 'Address Line 2',
    Your_Company: 'Your Company',
    Update_Profile: 'Update Profile',
    Enter_New_password: 'Enter New Password',
    Your_email_address: 'Your email address',
    Your_First_Name: 'Your First Name',
    Enter_Old_password: 'Enter Old Password',
    Your_Last_Name: 'Your Last Name',
    Sign_Up: 'Sign Up',
    Sign_In: 'Sign In',
    Order_Success: 'Order Success',
    Areas: 'Areas',
    Checkout: 'Checkout',
    Categories: 'Categories',
    Menu: 'Menu',
    Register: 'Register',
    All_Products: 'All Products',
    Terms_and_Conditions: 'Terms and Conditions',
    Privacy_Policy: 'Privacy Policy',
    Contact_Us: 'Contact Us',
    About_Us: 'About Us',
    Logout: 'Logout',
    Addresses: 'Addresses',
    Wallet: 'Wallet',
    Account_Details: 'Account Details',
    PRODUCT_ADDED_TO_CART: 'Product is added to your cart successfully',
    Product_Added_to_Wishlist: 'Product Added to Wishlist',
    Product_Removed_From_Wishlist: 'Product Removed From Wishlist',
    SUCCESS: 'success',
    Removed: 'Removed',
    chooseCar: 'CHOOSE CAR',
    new: 'NEW',
    used: 'USED',
    make: 'Make',
    model: 'Model',
    year: 'Year',
    search: 'Search',
    selectCar: 'SELECT CAR',
    configure: 'CONFIGURE',
    payOnline: 'PAY ONLINE',
    delivery: 'Delivery',
    featuredCar: 'FEATURED CARS',
    buyNow: 'Buy Now',
    finance: 'Finance',
    vatInc: 'VAT included',
    financingAvailable: 'Financing Available',
    butFrmEl_Ektiar: 'BUY FROM Al-Ektiar',
    financingOption: 'FINANCING OPTION',
    compitativePrices: 'COMPETITIVE PRICES',
    insuranceAvailable: 'INSURANCE AVAILABLE',
    guarenteedPurchase: 'GUARANTEED PURCHASE',
    home: 'HOME',
    Home: 'Home',
    financing: 'FINANCING',
    close: 'Close',
    promo: 'PROMO',
    completeOrder: 'COMPLETE ORDER',
    callBack: 'CALL BACK',
    selectMake: 'SELECT MAKE',
    selectModal: 'SELECT MODEL',
    selectYear: 'SELECT YEAR',
    color: 'Color',
    payNow: 'Pay Now',
    applyForFinance: 'Apply for Finance',
    payFullAmount: 'Pay Full',
    payDeposit: 'Pay Deposit',
    procedToCheckout: 'Proceed to Checkout',
    overView: 'OVERVIEW',
    features: 'Features',
    whyBuyFrmEl_Ektiar: 'WHY BUY FROM AL-EKTIAR',
    customerReview: 'Customer Reviews',
    similarVehicles: 'Similar Vehicles',
    enquireNow: 'Enquire Now',
    brochure: 'Brochure',
    orders: 'Orders',
    testimonials: 'Testimonials',
    termCondtions: 'Term and Condtions',
    privacyPolicy: 'Privacy Policy',
    faq: 'FAQ',
    securePayment: 'Secure Payment',
    contactUs: 'Contact Us',
    email: 'Email',
    telephone: 'Telephone',
    phone: 'Phone',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    login: 'Sign In',
    forgotPassword: 'Forgot Password',
    signUp: 'Sign Up',
    showMore: 'Show More',
    share: 'Share',
    aboutUs: 'About Us',
    addTestimonial: 'Add Testimonial',
    insurance: 'Insurance',
    standard: 'Standard',
    premium: 'Premium',
    vas: 'VAS',
    shiping: 'shipping',
    payments: 'Payments',
    roadRecovery: 'Road Recovery',
    next: 'Next',
    tinting: 'Tinting',
    back: 'Back',
    BackWithIcon: '< Back',
    total: 'Total',
    vat: 'VAT',
    vehiclePrice: 'Vehicle Price',
    valeAddService: 'Value Added Service',
    orderNow: 'Order Now',
    cart: 'Cart',
    wishList: 'WishList',
    account: 'Account',
    save: 'Save',
    myOrders: 'My Orders',
    orderTotal: 'Order Total',
    viewOrder: 'View Order',
    reorder: 'Reorder',
    date: 'Date',
    account_information: 'account information',
    firstName: 'First Name',
    lastName: 'Last Name',
    change_email: 'Change Email',
    change_password: 'Change Password',
    confirm_password: 'Confirm Password',
    new_password: 'New Password',
    current_password: 'Current Password',
    name: 'Name',
    preferred_mode_of_contact: 'Preferred mode of contact',
    mobile: 'Mobile',
    mobile_number: 'Mobile Number',
    please_describe_your_enquiry: 'Please describe your enquiry',
    submit_enquiry: 'Submit Enquiry',
    login_to_your_account: 'Login to your Account',
    login_with: 'Login with',
    did_not_have_an_account: "Don't have an account",
    order_successfully_placed: 'order successfully placed',
    thank_you_for_purchase: 'Thank you for shopping with us',
    payment_status: 'payment status',
    my_account: 'My Account',
    you_can_track_your_order_by_clicking_on:
      'You can track your order by clicking on',
    not_ready_to_buy_online_call_us: 'Not ready to buy online? Call Us',
    request_a_call_back: 'Request A Callback',
    request_a_quote: 'Request a Quote',
    free_service_from_el_ekhtiar: 'Free service from Al-Ektiar',
    create_your_account: 'Create your Account',
    already_have_an_account: 'Already have an Account',
    my_wishList: 'my wishList',
    supporting_documents: 'Supporting Documents',
    salary_certificate: 'Salary Certificate',
    browse: 'Browse',
    id_copy: 'I.D copy',
    igama: 'Igama',
    driving_license: 'Driving license',
    cost_certificate: 'Cost Certificate',
    your_cart_is_empty: 'YOUR CART IS EMPTY',
    here_to_help: 'HERE TO HELP',
    contact_us_by_email: 'Contact Us By Email',
    customer_care: 'Customer Care',
    contact_us_by_phone: 'Contact Us By Phone',
    my_billing_and_shipping_address_are_the_same:
      'My billing and shipping address are the same',
    phone_number: 'Phone Number',
    address: 'Address',
    street_address: 'Street',
    state: 'State/Province',
    city: 'City',
    avenue:'Avenue',
    house_field:'Building/Home',
    floor:'Floor',
    flat:'Flat',
    country: 'Country',
    zip_postal_code: 'Zip/Postal Code',
    shipping_method: 'Shipping Method',
    select_showroom: 'Select Showroom',
    about: 'About',
    yourOrder: 'Your Order',
    specialOffers: 'Special Offers',
    profile: 'Profile',
    offers: 'Offers',
    locations: 'Locations',
    availThisOffer: 'Avail This Offer',
    searchNow: 'Search Now',
    selectAll: 'Select All',
    default: 'Default',
    if_salary_not_credit_to_same_bank: 'If salary not credit to same bank',
    bank_statement_for_last_3_months: 'bank statement for last 3 months',
    all_other_mentioned_documents: 'all other mentioned documents',
    lorem_ipsum_has_been_the_industrys_standard_dummy_text_ever_since_the_1500s:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
    select: 'Select',
    incl: 'incl',
    terms_and_conditions: 'Terms & Conditions',
    i_agreed_this_terms: 'I Agreed this Terms',
    payment_methods: 'Payment Methods',
    payment_method: 'Payment Method',
    there_are_no_payment_methods_for_this_address:
      'There are no payment methods for this address',
    you_will_be_redirected_to: 'You will be redirected to',
    al_rajhi_bank: 'Al Rajhi Bank',
    portal: 'portal',
    your_new_vehicle: 'Your New Vehicle',
    included: 'Included',
    you: 'You',
    by_checking_this_you_are_agree_to_the_terms_and_conditions_and_are_entering_into_an_agreement_to_purchase:
      'By checking this you are agree to the terms & conditions and are entering into an agreement to purchase',
    a_car_from_wallan_which_is_legally_binding:
      'a car from Wallan which is legally binding',
    there_are_no_shipping_methods_for_this_address:
      'There are no shipping methods for this address',
    shipping_address: 'Shipping Address',
    chane_address: 'Change address',
    new_address: 'NEW ADDRESS',
    please_enter_your: 'Please enter your',
    information_saved_successfully: 'Information saved successfully',
    information_and_password_changed_successfully:
      'Information and password changed successfully',
    please_add_valid_information: 'Please add valid information',
    company: 'Company',
    submit: 'Submit',
    no_address_found: 'No address found',
    maintain_your_task_here: 'Maintain your task here',
    task: 'task',
    additional_comments: 'additional comments',
    preferred_time_to_call: 'Preferred Time to Call',
    reason_for_call_back: 'Reason For Call Back',
    any_additional_omment: 'Any Additional Comment',
    news_and_updates: 'News & Updates',
    it_is_a_long_established_fact_that_a_reader_will_be_distracted_by_the_readable_content_of_a_page_when_looking_at_its_layout_The_point_of_using_Lorem_Ipsum_is_that_it_has_a_more_or_less_normal_distribution_of_letters_as_opposed_to_using_Content_here_content_here_making_it_look_like_readable_English:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
    yes_subscribeme_to_ElEltiar_NewsLetters:
      'Yes, subscribe to Al-Ektiar NewsLetters',
    title: 'Title',
    mr: 'Mr.',
    mrs: 'Mrs.',
    miss: 'Miss.',
    coming_soon: 'Coming soon',
    your_order_is_empty: 'YOUR ORDER IS EMPTY',
    an_email_has_been_sent_to_your_account_Please_verify_that_mail:
      'An email has been sent to your account. Please verify that mail.',
    this_email_does_not_belong_to_any_account:
      'This email does not belong to any account',
    please_enter_your_email_address_below_to_receive_a_password_reset_link:
      'Please enter your email address below to receive a password reset link.',
    reset_my_password: 'Reset My Password',
    order_date: 'Order Date',
    item_ordered: 'ITEMS ORDERED',
    sku: 'Sku',
    qty: 'Qty',
    price: 'Price',
    subtotal: 'Subtotal',
    shiping_and_handling: 'Shiping & Handling',
    tax_amount: 'Tax Amount',
    grand_total: 'GRAND TOTAL',
    order_information: 'ORDER INFORMATION',
    billing_address: 'Billing Address',
    your_order: 'Your Order',
    is_Recieved_with: 'is Recieved with',
    full_payment_recevied: 'full payment recevied',
    A_confirmation_Email_and_SMS_has_been_sent_to_contact_details_below:
      'A confirmation Email and SMS has been sent to contact details below.',
    Share_your_experiance_to_help_others:
      'Share your experiance to help others.',
    How_I_can_apply_for_finance: 'How I can apply for finance.',
    rate: 'Rate',
    Post_Review: 'Post Review',
    localizationYou_already_have_a_car_in_your_cart_Would_you_like_to_remove_the_exiting_car_from_the_cart_and_add_this_car:
      'You already have a car in your cart. Would you like to remove the exiting car from the cart and add this car.',
    review: 'Review',
    Down_Payment: 'Down Payment',
    term: 'Term',
    months: 'Months',
    for_more_than_1_car: '(for more than 1 car)',
    write_a_review: 'Write a review',
    email_Address: 'Email Address',
    enter_your_comment: 'Enter Your Comment',
    i_have_read_and_accept: 'I have read and accept',
    use_as_my_default_billing_address: 'Use as my default billing address',
    use_as_my_default_shipping_address: 'Use as my default shipping address',
    sort: 'Sort',
    filter: 'Filter',
    'Filter By': 'Filter By',
    cars: 'Cars',
    found: 'Found',
    no_record_found: 'No record found',
    position: 'Position',
    product_name: 'Product Name',
    apply_filters: 'Apply Filters',
    password_does_not_match: 'Password does not match',
    user_is_successfully_registered: 'User is successfully registered.',
    summary: 'Summary',
    your_request_has_been_submitted: 'Your request has been submitted',
    rating: 'Rating',
    talk_about_why_you_like_this_review: 'Talk about why you like this review',
    talk_about_why_you_dislike_this_review:
      'Talk about why you dislike this review',
    add: 'Add',
    select_show_room: 'Select Showroom',
    user_authentication_failed: 'User authentication failed',
    please_login_again: 'Please login again',
    please_select: 'Please select',
    show_room: 'Show room',
    engine: 'Engine',
    please_write_details_of_experience: 'Please write details of experience',
    thank_you_for_your_feedback: 'Thank you for your feedback.',
    please_select_car_colour: 'Please select car colour',
    share_details_of_your_own_experiance:
      'Share details of your own experiance...',
    you_have_already_selected_a_car: "You've already selected a car",
    keep_it: 'Keep it',
    remove_existing_car: 'Remove existing car',
    minimum_deposit_is: 'Minimum deposit is',
    processing_fee: 'Processing Fee',
    cash_price: 'Cash Price',
    down_payment: 'Down Payment',
    loan_payment: 'Loan Payment',
    or: 'Or',
    pay_by_credit_cards: 'Pay by Credit Card',
    log_out: 'Log out',
    change_language: 'Change Language',
    multi: 'Multi',
    personal_information: 'Personal Information',
    email_is_invalid: 'Email is invalid',
    'Email is Invalid': 'Email is invalid',
    is_removed_from_wishlist: 'is removed from wishlist.',
    is_added_into_wishlist: 'is added into wishlist.',
    what_are_you_looking_for: 'What are you looking for?',
    all_orders: 'All Orders',
    fullpayment_rders: 'Full Payment Orders',
    split_payments_orders: 'Split Payments Orders',
    financed_orders: 'Financed Orders',
    my_support_tickets: 'My Support Tickets',
    apply_now: 'Apply Now',
    recommendedCars: 'Recommended Cars',
    compare: 'Compare',
    specialPrice: 'Special Price for Cash Customer',
    payInCash: 'Pay in Cash',
    outstandingPayments: 'Outstanding Payments',
    pay_deposit_note:
      'Note: Clear Your cart before making part payment, otherwise quote will be truncated.',
    note: 'NOTE',
    product_details_note:
      'Mandatory Car Insurance charges are NOT included in the stated Total Car price. Customer can himself arrange Insurance for the purchased car or AlEktiar can also facilitate the customer in purchasing car Insurance with additional charges that will be paid by the customer.',
    finance_bank_note:
      'Please provide your choices for Bank , Down Payment , Final Payment, Which would become inputs to your financing application.',
    have_any_queries: 'Have any queries? Try our',
    or_call_us: 'or Call us',
    rate_and_review: 'Rate & Review',
    contact_date: 'Contact Date',
    contact_time: 'Contact Time',
    number_of_cars_required: 'Number Of Cars Required',
    brief_overview: 'Brief Overview ',
    overview_desc:
      'If quote for more than one car type/model is required, please provide details here',
    phone_number_is_invalid: 'Mobile number is invalid',
    extras: 'Extras',
    select_extras: 'SELECT EXTRAS',
    extras_desc:
      'Select the required Extras; Prices shown are inclusive of VAT',
    registration_charges: 'Registration Charges',
    deposit_amount: 'Deposit Amount',
    remaining_amount: 'Remaining Amount',
    financed_amount: 'Financed Amount',
    monthly_installment: 'Monthly Installment',
    delivery_instruction:
      'Please take note that car delivery can only be made to the person on whose name the car is to be registered.',
    map_instruction: 'Please select the map pin according to your address.',
    locate_me: 'Locate Me',
    shipping_policy: 'Shipping Policy',
    supporting_documnet: 'Supporting Documents',
    start_condition: 'By checking this I have read and agree to the',
    end_condition:
      'and that I willingly entering into an agreement to purchase a car from Al Ektiar which is legally binding',
    apply_discount_code: 'Apply Discount Code',
    enter_discount_code: 'Enter discount code',
    apply: 'Apply',
    remove: 'Remove',
    cart_emty_desc:
      'Your cart is currently empty, please select a car you would like to purchase',
    cart_desc:
      'Need help about our services? Contact us now and we get back to you shortly.',
    create_ticket: 'Create Ticket',
    subject: 'Subject',
    department: 'Department',
    last_activity: 'Last Activity',
    view_issue: 'View Issue',
    closed: 'Closed',
    open: 'Open',
    details: 'Details',
    request_id: 'Request ID',
    priority: 'Priority',
    status: 'Status',
    order: 'Order',
    message: 'Message',
    load_previous_messages: 'Load previous messages',
    close_ticket: 'Close Ticket',
    submit_ticket: 'Submit Ticket',
    history: 'History',
    ticket_close_successfully: 'Your ticket has been closed successfully',
    message_posted_successfully: 'Your message was successfully posted',
    please_enter_a_message: 'Please enter message!!',
    post_a_reply: 'Post a Reply',
    update: 'Update',
    terms_months: 'Terms / Months',
    loan_amount: 'Loan Amount',
    administrative_fee: 'Administrative Fee',
    finance_cost: 'Finance Cost',
    profit_margin_ratio: 'Profit Margin Ratio',
    total_profits: 'Total Profits',
    total_insurance: 'Total Insurance',
    total_comprehensive: 'Total Comprehensive',
    total_interest_value: 'Total Interest Value',
    total_downpayment: 'Total Downpayment',
    total_deduction: 'Total Deduction',
    allowed_premium: 'Max. Allowed Premium',
    ncb: 'NCB (AlAhli)',
    final_payment: 'Final Payment',
    enter_location: 'Enter Location',
    coupon_applied_successfully: 'Your coupon was successfully applied.',
    coupon_removed_successfully: 'Your coupon was successfully removed.',
    something_went_wrong: 'Something went wrong! Please try again.',
    please_accept_tems: 'Please accept terms & conditions.',
    pleae_select_payment_methods: 'Please select payment method',
    sorry_loacation_is_outside_saudi_arabia:
      'Sorry, Location is Outside of Saudi Arabia',
    you_are_successfully_logged_in: 'You are successfully logged in !!!',
    please_login_to_your_account: 'Please login to your account',
    you_are_successfully_logged_out: 'You are successfully logged out.',
    comparison: 'Comparison',
    tickets: 'Tickets',
    ticket_details: 'Ticket Details',
    verify_otp: 'Verify OTP',
    your_cart: 'Your Cart',
    address_deleted_successfully: 'Address deleted successfully',
    select_an_order: 'Select an Order',
    ticket_posted_successfully: 'Your ticket was successfully posted',
    you_have_placed_no: 'You have placed no',
    please_enter_amount: 'Please enter amount',
    request_forwarded: 'Your request was forwarded to concerned department.',
    error_type: 'Error Type',
    report_description: 'REPORT DESCRIPTION',
    error_description: 'Error Description',
    send: 'Send',
    request_an_extension: 'Request an extension',
    you_till_have: 'You have till',
    to_pay_the_remaining_amount: 'to pay the remaining amount.',
    report_an_error: 'Report an Error',
    make_your_payment: 'Make Your Payment',
    signin_mob_number: 'Signin Mobile Number',
    otp_sent_note:
      'Note: Please do not refresh the page. An SMS with OTP was sent on your provided mobile number. Please enter it in the OTP field.',
    enter_otp: 'Enter OTP',
    continue: 'Continue',
    send_otp: 'Send OTP',
    resend_otp: 'Resend OTP',
    verification: 'Verification',
    verify: 'Verify',
    'All Products': 'All Products',
    'Best Sellers Products': 'Best Sellers Products',
    'Office & Student Supplies': 'Office & Student Supplies',
    'Learning and Education': 'Learning and Education',
    'My Account': 'My Account',
    'Privacy Policy': 'Privacy Policy',
    'Terms & Conditions': 'Terms & Conditions',
    'Login/Register': 'Login/Register',
    'Forgot Password?': 'Forgot Password?',
    'Forgot Password': 'Forgot Password',
    'About Us': 'About Us',
    FAQ: 'FAQ',
    'Returns and Exchange': 'Returns and Exchange',
    'Contact Us': 'Contact Us',
    Hello: 'Hello',
    Search: 'Search',
    'Billing Details': 'Billing Details',
    'Shipping Details': 'Shipping Details',
    'Ship to Different Address?': 'Ship to Different Address?',
    'Order notes (Optional)': 'Order notes (Optional)',
    'First Name': 'First Name',
    'Last Name': 'Last Name',
    'Country: Kuwait': 'Country: Kuwait',
    Area: 'Area',
    'Address 1': 'Address 1',
    'Address 2 (Optional)': 'Address 2 (Optional)',
    City: 'City',
    Postcode: 'Postcode',
    Email: 'Email',
    'Email address': 'Email address',
    Phone: 'Phone',
    Shipping: 'Shipping',
    'My Order': 'My Order',
    Subtotal: 'Subtotal',
    item: 'item',
    items: 'items',
    Item: 'Item',
    Items: 'Items',
    Cart: 'Cart',
    Back: 'Back',
    Total: 'Total',
    'Same Day Delivery': 'Same Day Delivery',
    'Next Day Delivery': 'Next Day Delivery',
    'No Products Found': 'No Products Found',
    Orders: 'Orders',
    WishList: 'WishList',
    'Account Details': 'Account Details',
    'Thank you': 'Thank you',
    'Your order has been received': 'Your order has been received',
    'Balance Remaining': 'Balance Remaining',
    'Amount entered exceeds your wallet balance':
      'Amount entered exceeds your wallet balance',
    Amount: 'Amount',
    'Form Incomplete': 'Form Incomplete',
    'Please fill in': 'Please fill in',
    'for billing': 'for billing',
    'for shipping': 'for shipping',
    'Rather not say': 'Rather not say',
    'No Code': 'No Code',
    'Please enter a valid coupon code': 'Please enter a valid coupon code',
    'Invalid Stock': 'Invalid Stock',
    'There are only': 'There are only',
    left: 'left',
    'Out Of Stock': 'Out Of Stock',
    'is not in stock right now please check after sometime':
      'is not in stock right now please check after sometime',
    'Form Invalid': 'Form Invalid',
    'Please insert email or username': 'Please insert email or username',
    'Reset Password': 'Reset Password',
    'Reset Link Sent to Email': 'Reset Link Sent to Email',
    'Please insert password': 'Please insert password',
    'Passwords are not the same': 'Passwords are not the same',
    'Please insert username': 'Please insert username',
    'Please insert email': 'Please insert email',
    Oops: 'Oops',
    'You must be logged in to add product in wishlist!':
      'You must be logged in to add product in wishlist!',
    'Subscribe for InStock Notification?':
      'Subscribe for InStock Notification?',
    'Added to Cart': 'Added to Cart',
    Subscribe: 'Subscribe',
    Subscribed: 'Subscribed',
    Newness: 'Newness',
    Invalid: 'Invalid',
    'You must be logged in to review a product.':
      'You must be logged in to review a product.',
    'Minimum Order': 'Minimum Order',
    'Minimum order of KD': 'Minimum order of KD',
    'is required': 'is required',
    'Please insert Review for the Product':
      'Please insert Review for the Product',
    'Rate Product': 'Rate Product',
    'Are you sure you give 1 stars for this product?':
      'Are you sure you give 1 stars for this product?',
    'Limited Quantity': 'Limited Quantity',
    'available right now.': 'available right now.',
    'Update?': 'Update?',
    Update: 'Update',
    'is not in stock right now please check after sometime!':
      'is not in stock right now please check after sometime!',
    'Empty Cart': 'Empty Cart',
    'Would you like to remove all products from the cart?':
      'Would you like to remove all products from the cart?',
    'Delete?': 'Delete?',
    'Subscribe for In-Stock Notification?':
      'Subscribe for In-Stock Notification?',
    Delete: 'Delete',
    'Delete & Subscribe': 'Delete & Subscribe',
    'Coupon Applied Successfully': 'Coupon Applied Successfully',
    Sorry: 'Sorry',
    'This coupon is not applicable to selected products.':
      'This coupon is not applicable to selected products.',
    'Coupon not available': 'Coupon not available',
    'Coupon Not Found': 'Coupon Not Found',
    'Please enter valid wallet amount': 'Please enter valid wallet amount',
    Payment: 'Payment',
    'Cash on Delivery': 'Cash on Delivery',
    'Place Order': 'Place Order',
    'Only Cash on Delivery is supported at the moment.':
      'Only Cash on Delivery is supported at the moment.',
    'Addresses have been successfully updated':
      'Addresses have been successfully updated',
    'Please fill in first name': 'Please fill in first name',
    'Please fill in last name': 'Please fill in last name',
    'Please fill in email': 'Please fill in email',
    'Please fill in display name': 'Please fill in display name',
    "Current password can't be empty!": "Current password can't be empty!",
    "New password can't be empty!": "New password can't be empty!",
    "Re-Enter New password can't be empty!":
      "Re-Enter New password can't be empty!",
    'New password and Re-Enter New password not matching!':
      'New password and Re-Enter New password not matching!',
    'Account Details have been updated successfully':
      'Account Details have been updated successfully',
    'There are only %d %@ left': 'There are only %d %@ left',
    'Username or Email': 'Username or Email',
    Password: 'Password',
    Username: 'Username',
    'Repeat Password': 'Repeat Password',
    'Date of Birth': 'Date of Birth',
    'Mobile No.': 'Mobile No.',
    Taimaa: 'Taimaa',
    Doha: 'Doha',
    Sulaibiya: 'Sulaibiya',
    Waha: 'Waha',
    Jahra: 'Jahra',
    'Saad Al-Abdullah': 'Saad Al-Abdullah',
    Qasr: 'Qasr',
    Oyoun: 'Oyoun',
    Naseem: 'Naseem',
    Naeem: 'Naeem',
    Farwaniya: 'Farwaniya',
    Rigai: 'Rigai',
    Khaitan: 'Khaitan',
    'Abdullah Al-Mubarak': 'Abdullah Al-Mubarak',
    Andalous: 'Andalous',
    Variation_not_selected:'Please select product options before placing this product in the shopping cart',
    Firdous: 'Firdous',
    'Sabah Al-Nasser': 'Sabah Al-Nasser',
    Ardiya: 'Ardiya',
    Rai: 'Rai',
    Ishbilya: 'Ishbilya',
    'Jleeb Al-Shuyoukh': 'Jleeb Al-Shuyoukh',
    Rehab: 'Rehab',
    Rabia: 'Rabia',
    Omariya: 'Omariya',
    'Al-Dajeej': 'Al-Dajeej',
    'Ali Sabah Al-Salem': 'Ali Sabah Al-Salem (Um Al-Haiman)',
    'Sabah Al-Ahmad': 'Sabah Al-Ahmad',
    Mangaf: 'Mangaf',
    'Khiran Residential': 'Khiran Residential',
    'Mubarak Al-Abdullah': 'Mubarak Al-Abdullah (West Mishref)',
    Mahboula: 'Mahboula',
    'Jaber Al-Ali': 'Jaber Al-Ali',
    Hadiya: 'Hadiya',
    Fintas: 'Fintas',
    Fahaheel: 'Fahaheel',
    'Fahad Al-Ahmad': 'Fahad Al-Ahmad',
    Eqaila: 'Eqaila',
    Assabahiya: 'Assabahiya',
    'Al-Riqqa': 'Al-Riqqa',
    Dahar: 'Dahar',
    Ahmadi: 'Ahmadi',
    'Abu Halifa': 'Abu Halifa',
    'Sabah Al-Salem': 'Sabah Al-Salem',
    Fnaitees: 'Fnaitees',
    Qurain: 'Qurain',
    'Mubarak Al-Kabeer': 'Mubarak Al-Kabeer',
    Messila: 'Messila',
    Qusor: 'Qusor',
    'Al-Masayel': 'Al-Masayel',
    Adan: 'Adan',
    'Abu Fatira': 'Abu Fatira',
    'Abu Al-Hasaniya': 'Abu Al-Hasaniya',
    Zahra: 'Zahra',
    Hateen: 'Hateen',
    Salam: 'Salam',
    Shuhada: 'Shuhada',
    Siddeeq: 'Siddeeq',
    'Maidan Hawalli': 'Maidan Hawalli',
    Jabriya: 'Jabriya',
    Hawalli: 'Hawalli',
    Shaab: 'Shaab',
    Salwa: 'Salwa',
    Salmiya: 'Salmiya',
    Rumaithiya: 'Rumaithiya',
    Mishref: 'Mishref',
    Bayan: 'Bayan',
    'Al-Bidea': 'Al-Bidea',
    Rawda: 'Rawda',
    'North West Al-Sulaibikhat': 'North West Al-Sulaibikhat',
    Sulaibikhat: 'Sulaibikhat',
    'Jaber Al-Ahmad': 'Jaber Al-Ahmad',
    Granada: 'Granada',
    Qairawan: 'Qairawan',
    Nahdha: 'Nahdha',
    'Bneid Al-Gar': 'Bneid Al-Gar',
    Khaldiya: 'Khaldiya',
    Surra: 'Surra',
    Yarmouk: 'Yarmouk',
    'Shuwaikh Residential': 'Shuwaikh Residential',
    Qortuba: 'Qortuba',
    Adailiya: 'Adailiya',
    Kaifan: 'Kaifan',
    Faiha: 'Faiha',
    Shamiya: 'Shamiya',
    Qibla: 'Qibla',
    Qadsiya: 'Qadsiya',
    Nuzha: 'Nuzha',
    Sharq: 'Sharq',
    Dasma: 'Dasma',
    Daiya: 'Daiya',
    'Kuwait City': 'Kuwait City',
    Mansouriya: 'Mansouriya',
    'Abdullah Al-Salem': 'Abdullah Al-Salem',
    'Registering with Hadafy you agree to our':
      'Registering with Hadafy you agree to our',
    and: 'and',
    'Musical Instruments':"Musical Instruments",
    'Perfume':"Perfume",
    'Baby & Mother':"Baby & Mother",
    'Sport & Outdoor':"Sport & Outdoor",
    'Toys':"Toys",
    'Household Supplies':"Household Supplies",
    'Electronics':"Electronics",
    'Watches & Jewelry':"Watches & Jewelry",
    'Home & Furniture':"Home & Furniture",
    'Beauty & Personal Care':"Beauty & Personal Care",
    'Featured Products':"Featured Products",
    'Camping Season':"Camping Season",
    'Year End Sale':"Year End Sale",
    'Delete My Account': "Delete My Account",
    'ACCOUNT_DELETED':"Account Deleted",
    'Delete Account': "Delete Account",
    'Delete_confirm':"Are you sure you want to delete your account",
    'deleted_account_recovery':'It can be recovered in 14 days if it is deleted accidently.',
    phone_length_error: 'Telephone length should be less than 8',
    dont_enter_code_error:'Do not add country code with the mobile number'
  },
  ar: {
    dont_enter_code_error:'لا تقم بإضافة رمز الدولة مع رقم الهاتف المحمول',
    phone_length_error:'يجب أن يكون طول الهاتف أقل من 8',
    'Delete My Account': "حذف حسابي",
    'ACCOUNT_DELETED':"تم حذف حسابك",
    'Delete_confirm':"هل انت متأكد انك تريد حذف حسابك",
    'Delete Account': "حذف الحساب",
    'deleted_account_recovery':'يمكن استردادها في غضون 14 يومًا إذا تم حذفها عن طريق الخطأ.',
    'Musical Instruments':"الاجهزة الموسيقية",
    'Perfume':"العطور",
    'Baby & Mother':"الطفل والأم",
    'Sport & Outdoor':"الرياضة والأنشطة الخارجية",
    'Toys':"ألعاب الأطفال",
    'Household Supplies':"اللوازم المنزلية",
    'Electronics':"إلكترونيات",
    'Watches & Jewelry':"ساعات ومجوهرات",
    'Home & Furniture':"الأثاث المنزلي",
    'Beauty & Personal Care':"الجمال والعناية الشخصية",
    'Featured Products':"منتجات مميزة",
    'Camping Season':"موسم المخيّمات",
    'Year End Sale':"عروض وخصومات كبيرة ومميزة",
    'has already been applied and cannot be used in conjunction with other coupons.': 'تم تطبيقه بالفعل ولا يمكن استخدامه مع القسائم الأخرى.',
    'Sorry, coupon': "آسف قسيمة",
    Retry: 'Retry',
    'View Product': 'View Product',
    'Selected for Comparison': 'Selected for Comparison',
    'Al Asimah': 'Al Asimah',
    'Abdullah Al-Salem': 'Abdullah Al-Salem',
    Adailiya: 'Adailiya',
    'Bneid Al Qar': 'Bneid Al Qar',
    Daiya: 'Daiya',
    Dasma: 'Dasma',
    Dasman: 'Dasman',
    Doha: 'Doha',
    Faiha: 'Faiha',
    Ghornata: 'Ghornata',
    'Jaber Al Ahmad': 'Jaber Al Ahmad',
    Kaifan: 'Kaifan',
    Khaldiya: 'Khaldiya',
    'Kuwait City': 'Kuwait City',
    Mansouriya: 'Mansouriya',
    Mirqab: 'Mirqab',
    'Mubarakiya Camps': 'Mubarakiya Camps',
    Nahda: 'Nahda',
    'North West Sulaibikhat': 'North West Sulaibikhat',
    Nuzha: 'Nuzha',
    Qadsiya: 'Qadsiya',
    Qibla: 'Qibla',
    Qortuba: 'Qortuba',
    Rawda: 'Rawda',
    Salhiya: 'Salhiya',
    Shamiya: 'Shamiya',
    Sharq: 'Sharq',
    'Shuwaikh Administrative': 'Shuwaikh Administrative',
    'Shuwaikh Educational': 'Shuwaikh Educational',
    'Shuwaikh Industrial 1': 'Shuwaikh Industrial 1',
    'Shuwaikh Industrial 2': 'Shuwaikh Industrial 2',
    'Shuwaikh Industrial 3': 'Shuwaikh Industrial 3',
    'Shuwaikh Medical': 'Shuwaikh Medical',
    'Shuwaikh Residential': 'Shuwaikh Residential',
    Shuwaikh: 'Shuwaikh',
    Sulaibikhat: 'Sulaibikhat',
    Surra: 'Surra',
    Yarmouk: 'Yarmouk',
    Hawali: 'Hawali',
    'Al-Bedae': 'Al-Bedae',
    Bayan: 'Bayan',
    Hawally: 'Hawally',
    Hitteen: 'Hitteen',
    Jabriya: 'Jabriya',
    'Maidan Hawally': 'Maidan Hawally',
    'Ministries Zone': 'Ministries Zone',
    Mishrif: 'Mishrif',
    'Mubarak Al-Abdullah - West Mishref': 'Mubarak Al-Abdullah - West Mishref',
    Rumaithiya: 'Rumaithiya',
    Salam: 'Salam',
    Salmiya: 'Salmiya',
    Salwa: 'Salwa',
    Shaab: 'Shaab',
    Shuhada: 'Shuhada',
    Siddiq: 'Siddiq',
    Zahra: 'Zahra',
    'Al Farwaniyah': 'Al Farwaniyah',
    'Abdullah Al-Mubarak': 'Abdullah Al-Mubarak',
    Airport: 'Airport',
    Andalous: 'Andalous',
    'Ardhiya 4': 'Ardhiya 4',
    Ardhiya: 'Ardhiya',
    'Ardiya Small Industrial': 'Ardiya Small Industrial',
    'Ardiya Storage Zone': 'Ardiya Storage Zone',
    Ashbeliah: 'Ashbeliah',
    Dhajeej: 'Dhajeej',
    Farwaniya: 'Farwaniya',
    Ferdous: 'Ferdous',
    'Jeleeb Al-Shuyoukh': 'Jeleeb Al-Shuyoukh',
    Khaitan: 'Khaitan',
    Omariya: 'Omariya',
    Rabiya: 'Rabiya',
    Rai: 'Rai',
    Reggai: 'Reggai',
    Rehab: 'Rehab',
    'Sabah Al-Nasser': 'Sabah Al-Nasser',
    'Sheikh Saad Al Abdullah Airport': 'Sheikh Saad Al Abdullah Airport',
    'Mubarak Al-Kabeer': 'Mubarak Al-Kabeer',
    'Abu Ftaira': 'Abu Ftaira',
    'Abu Hasaniya': 'Abu Hasaniya',
    Adan: 'Adan',
    'Al Masayel': 'Al Masayel',
    'Al-Qurain': 'Al-Qurain',
    'Al-Qusour': 'Al-Qusour',
    Fnaitess: 'Fnaitess',
    Messila: 'Messila',
    'Mubarak Al-Kabir': 'Mubarak Al-Kabir',
    'Sabah Al-Salem': 'Sabah Al-Salem',
    'Sabhan Industrial': 'Sabhan Industrial',
    'South Wista': 'South Wista',
    'West Abu Fetera Small Indust': 'West Abu Fetera Small Indust',
    Wista: 'Wista',
    'Al Jahra': 'Al Jahra',
    'Al Naeem': 'Al Naeem',
    'Jahra Amgarah Industrial': 'Jahra Amgarah Industrial',
    'Jahra Area': 'Jahra Area',
    Kabd: 'Kabd',
    Alnasseem: 'Alnasseem',
    Aloyoun: 'Aloyoun',
    Alqasr: 'Alqasr',
    'Saad Al Abdullah': 'Saad Al Abdullah',
    'Alsulaibiya Industrial 1': 'Alsulaibiya Industrial 1',
    'Alsulaibiya Industrial 2': 'Alsulaibiya Industrial 2',
    Alsulaibiya: 'Alsulaibiya',
    Taima: 'Taima',
    Alwaha: 'Alwaha',
    Alqairawan: 'Alqairawan',
    'Al Ahmadi': 'Al Ahmadi',
    'Abu Halifa': 'Abu Halifa',
    'Al-Ahmadi': 'Al-Ahmadi',
    'Ali Sabah Al-Salem - Umm Al Hayman': 'Ali Sabah Al-Salem - Umm Al Hayman',
    'Al-Julaiaa': 'Al-Julaiaa',
    Bnaider: 'Bnaider',
    Dhaher: 'Dhaher',
    Egaila: 'Egaila',
    'Fahad Al Ahmed': 'Fahad Al Ahmed',
    Fahaheel: 'Fahaheel',
    Fintas: 'Fintas',
    Hadiya: 'Hadiya',
    'Jaber Al Ali': 'Jaber Al Ali',
    Khairan: 'Khairan',
    Magwa: 'Magwa',
    Mahboula: 'Mahboula',
    Mangaf: 'Mangaf',
    'Mina Abdullah': 'Mina Abdullah',
    Nuwaiseeb: 'Nuwaiseeb',
    Riqqa: 'Riqqa',
    'Sabah Al Ahmad Marine City': 'Sabah Al Ahmad Marine City',
    'Sabah AL Ahmad residential': 'Sabah AL Ahmad residential',
    Sabahiya: 'Sabahiya',
    'Shuaiba Port': 'Shuaiba Port',
    'South Sabahiya': 'South Sabahiya',
    'Wafra farms': 'Wafra farms',
    'Wafra residential': 'Wafra residential',
    Zour: 'Zour',
    'New Total: ': 'المجموع الجديد: ',
    Delivery: 'توصيل',
    'Local pickup': 'شاحنة محلية',
    'E-Payment through Credit card and Debit card':
      'الدفع الإلكتروني من خلال بطاقة الائتمان وبطاقة الخصم',
    'Online Payment: Master Visa Card': 'الدفع عبر الإنترنت: ماستر فيزا كارد',
    'Online Payment: K-NET': 'الدفع عبر الإنترنت: K-NET',
    'Pay with cash upon delivery.': 'Pay with cash upon delivery.',
    'Grand Total': 'المجموع الإجمالي',
    'Sub Total': 'المجموع الفرعي',
    Preferences: 'التفضيلات',
    'Following Items Not Available': 'العناصر التالية غير متوفرة',
    'Order Failed': 'فشل الطلب',
    'Free Shipping': 'الشحن مجانا',
    'Free shipping': 'الشحن مجانا',
    'Coupon Min Amount':
      'لا يمكن تطبيق هذه القسيمة إلا إذا كان المبلغ الإجمالي لسلة التسوق هو الحد الأقصى: ',
    'Coupon Max Amount':
      'لا يمكن تطبيق هذه القسيمة إلا إذا كان المبلغ الإجمالي لسلة التسوق هو الحد الأدنى: ',
    'Search Your Area': 'ابحث في منطقتك',
    'Select Area': 'حدد المنطقة',
    Yes: 'نعم',
    No: 'رقم',
    Sale: 'تخفيض السعر',
    'Add to Cart': 'أضف إلى السلة',
    'Return Policy': 'سياسة العائدات',
    'Delivery Policy': 'سياسة التوصيل',
    'Top Rated Products': 'المنتجات الأعلى تقييماً',
    'Already Added in Wishlist': 'أضيفت بالفعل في قائمة الرغبات',
    'Product Removed From Wishlist': 'تمت إزالة المنتج من قائمة الرغبات',
    'Wishlist Emptied': 'قائمة الرغبات فارغة',
    'Failed to Join Waitlist': 'فشل الانضمام إلى قائمة الانتظار',
    'Not Enough Stock Available': 'مخزون غير كافٍ متاح',
    'Product Quantity Cannot be Reduced': 'لا يمكن تقليل كمية المنتج',
    'Cart Emptied': 'سلة التسوق فارغة',
    'Product Removed From Cart': 'تمت إزالة المنتج من سلة التسوق',
    'No More Items': 'لا مزيد من العناصر',
    'Invalid Password': 'رمز مرور خاطئ',
    'Invalid Username': 'اسم مستخدم غير صحيح',
    'Set Language': 'لغة مجموعة',
    first_name: 'الاسم الاول',
    last_name: 'الاسم الأخير',
    username: 'اسم المستخدم',
    sku: 'SKU',
    short_description: 'وصف قصير',
    related_products:'منتجات ذات صله',
    'Order Detail': 'تفاصيل الطلب',
    Newsletter: 'النشرة الإخبارية',
    'Subscribe to Newsletter': 'اشترك في النشرة الإخبارية',
    Confirmation: 'تأكيد',
    'Your Order Has Been Placed': 'لقد تلقينا طلبك',
    'Your Order Is': 'رقم الطلب الخاص بك هو',
    thanksForPurchase: `شكرا لك على الشراء\n\nستتلقى رسالة بريد إلكتروني لتأكيد الطلب بها تفاصيل عن طلبك ورابط لتتبع تقدمه.`,
    'Continue Shopping': 'مواصلة التسوق',
    Building: 'بناء',
    'Secure Checkout': 'الخروج الآمن',
    Description: 'وصف',
    description: 'وصف',
    Reviews: 'المراجعات',
    'Flat rate Far Area':'معدل ثابت للمنطقة البعيدة',
    'Select Color': 'إختر لون',
    'Additional Information': 'معلومة اضافية',
    'Add Review': 'إضافة مراجعة',
    'Select Size': 'أختر الحجم',
    'Kuwait Online Shopping Store': 'متجر الكويت للتسوق عبر الإنترنت',
    'Shop Top Brand': 'تسوق أفضل العلامات التجارية',
    'Discount Code': 'الرقم التسلسلي للخصم',
    'Chat on WhatsApp': 'الدردشة على WhatsApp',
    'Continue as Guest': 'تواصل كضيف',
    'Sort by': 'صنف حسب',
    'Featured Categories': 'فئات مميزة',
    'Enter Name': 'أدخل الاسم',
    'Continue Without Login': 'تواصل بدون تسجيل الدخول',
    "Don't Have An Account?": 'ليس لديك حساب؟',
    'Already Have An Account?': 'هل لديك حساب؟',
    'Or Login With': 'أو تسجيل الدخول باستخدام',
    'Enter Password': 'أدخل كلمة المرور',
    'Customer Services': 'خدمة العملاء',
    'Compare Products': 'قارن بين المنتجات',
    Settings: 'إعدادات',
    'Website - Luma': 'Website - Luma',
    'Language - English': 'Language - English',
    'Currency - $ US Dollar': 'العملة - دولار أمريكي',
    'Account Information': 'معلومات الحساب',
    'Address Book': 'دليل العناوين',
    'Product Reviews': 'تعليقات المنتج',
    'Downloadable Product': 'منتج قابل للتنزيل',
    "What's New": 'ما هو الجديد',
    Popular: 'شائع',
    Featured: 'متميز',
    Women: 'امرأة',
    Men: 'رجال',
    Kids: 'صغار في السن',
    'See All': 'اظهار الكل',
    'Search Your Product': `ابحث في منتجك`,
    'Enter Your Email to Recieve Notification When Product Arrives':
      'أدخل بريدك الإلكتروني لتلقي إشعار عند وصول المنتج',
    'Enter Valid Email': 'أدخل بريد إلكتروني صالح',
    'Join Waitlist': 'تاريخ قائمة الانتظار',
    'Sold Out': 'نفذ',
    'Invalid First Name': 'الاسم الأول غير صالح',
    'Invalid Last Name': 'اسم العائلة غير صالح',
    'Invalid Company': 'شركة غير صالحة',
    'Invalid Adress': 'عنوان خاطئ',
    'Invalid City': 'مدينة غير صالحة',
    'Invalid State': 'حالة غير صالحة',
    'Invalid Postcode': 'رمز بريدي غير صالح',
    'Invalid Country': 'بلد غير صالح',
    'Invalid Email': 'بريد إلكتروني خاطئ',
    'Invalid Phone': 'رقم الهاتف غير صحيح',
    'Invalid Street': 'شارع غير صالح',
    'Invalid Block': 'كتلة غير صالحة',
    'Invalid Email or Password':'البريد الإلكتروني أو كلمة السر خاطئة',
    'You Cannot Use This Coupon': 'لا يمكنك استخدام هذه القسيمة',
    'Coupon Usage Limit Exceeded': 'تم تجاوز حد استخدام القسيمة',
    OK: 'موافق',
    'Sort by default': 'فرز افتراضيًا',
    'Go Back': 'عد',
    'Address 1': 'Address 1',
    'Address 2 (Optional)': 'Address 2 (Optional)',
    'Failed to Login': 'فشل في تسجيل الدخول',
    'Password is Invalid': 'كلمة المرور غير صالحة',
    Popularity: 'الشهرة',
    'Average Rating': 'متوسط التقييم',
    'Price Low': 'اقل سعر',
    'Price High': 'اعلى سعر',
    Latest: 'آخر',
    'Sort by Popularity': 'فرز حسب الشعبية',
    'Sort by Average Rating': 'فرز حسب متوسط التقييم',
    'Sort by Price Low': 'الترتيب حسب السعر المنخفض',
    'Sort by Price High': 'فرز حسب السعر مرتفع',
    'Sort by Latest': 'فرز حسب الأحدث',
    'Total Price must be above 5 KD to checkout':
      'يجب أن يكون السعر الإجمالي أعلى من 5 دينار كويتي للمغادرة',
    Cancel: 'يلغي',
    'Login to Post Review': 'تسجيل الدخول لنشر المراجعة',
    'Failed to Add Review': 'فشل إضافة المراجعة',
    'Review Added Successfully': 'تمت إضافة المراجعة بنجاح',
    'Not Logged In': 'لم تقم بتسجيل الدخول',
    'Please share your opinion regarding this product.':
      'يرجى مشاركة رأيك بشأن هذا المنتج.',
    'Write Your Review': 'اكتب مراجعتك',
    'Rate This Product': 'قيم هذا المنتج',
    'Select Date': 'حدد تاريخ',
    SaleEnded: 'انتهى البيع',
    Warning: 'تحذير',
    'This Coupon Can Only be Applied Alone. All Other Coupons will be removed':
      'يمكن تطبيق هذه القسيمة وحدها. ستتم إزالة جميع القسائم الأخرى',
    'Coupon Expired': 'القسيمة منتهية الصلاحية',
    Code: 'رمز',
    'Enter Coupon Code': 'أدخل رمز القسيمة',
    Discount: 'خصم',
    Invalid_coupon: 'قسيمة غير صالحة',
    'No Items Found': 'لم يتم العثور على العناصر',
    'No Reviews Found': 'لم يتم العثور على العناصر',

    'No Products found': 'لا توجد منتجات',
    Coupon: 'كوبون',
    No_Coupon_Available: 'لا قسيمة متاحة',
    Apply_Coupon: 'تطبيق القسيمة',
    '3D Canvas': 'قماش ثلاثي الأبعاد',
    '4-Colored Pens': '4-اقلام ملونة',
    'A4 Envelops': 'مغلفات A4',
    'Acrylic & Gouache Paints': 'دهانات الأكريليك والجواش',
    'Adhesives & Tapes': 'مواد لاصقة وأشرطة',
    'ALL Categories': 'جميع الفئات',
    'Arts & Crafts': 'الفنون والحرف',
    'Ballpoint & Rollerball Pens': 'أقلام حبر جاف وأقلام حبر جاف',
    Binders: 'المجلدات',
    'Binders & Folders': 'المجلدات والمجلدات',
    'Board Markers & Erasers': 'أقلام السبورة والمحايات',
    Books: 'كتب',
    Brands: 'العلامات التجارية',
    'Brushes & Palettes': 'الفرش واللوحات',
    Calculators: 'حاسبات',
    'Canvas & Pads': 'قماش وسادات',
    Chalk: 'الطباشير',
    'Chalks & Charcoals': 'طباشير وفحم',
    'Children Books': 'كتب اطفال',
    Clay: 'طين',
    Cleaners: 'عمال النظافة',
    'Clips & Pins': 'مقاطع ودبابيس',
    'Coloring Books': 'كتب التلوين',
    'Coloring Markers': 'علامات التلوين',
    'Coloring Pencils': 'أقلام تلوين',
    Correctors: 'المصححون',
    Crayons: 'أقلام تلوين',
    'Cut & Paste Books': 'قص ولصق الكتب',
    Cutters: 'القواطع',
    'Dividers & Pockets': 'المقسمات والجيوب',
    'Drawing & Coloring': 'الرسم والتلوين',
    'Drawing & Painting Pads': 'منصات الرسم والتلوين',
    Variation_not_selected:'الرجاء تحديد خيارات المنتج قبل وضع هذا المنتج في عربة التسوق',
    'Drawing Pens': 'أقلام الرسم',
    Envelops: 'مغلفات',
    'Erasers & Sharpeners': 'المحايات والمبرايات',
    'Fineliner & Sign Pens': 'فاين لاينر وأقلام تسجيل',
    'Flash Drives': 'ذاكرة فلاش',
    'Geometry Sets': 'مجموعات الهندسة',
    'Glues & Adhesives': 'الغراء والمواد اللاصقة',
    'Graphite & Mechanical Pencils': 'أقلام الرصاص الجرافيت والميكانيكية',
    Highlighters: 'قلم تحديد',
    'Learning & Education': 'التربية والتعليم',
    'Learning and Education': 'التربية والتعليم',
    'Letter Envelops': 'مغلف الرسالة',
    Locks: 'أقفال',
    'Looseleaf & Graph Paper': 'ورق رسم بياني فضفاض',
    Markers: 'علامات',
    'Mediums & Varnishes': 'الوسائط والورنيشات',
    'Notebooks & Memos': 'الدفاتر والمذكرات',
    'Notebooks & Papers': 'دفاتر وأوراق',
    'Office and Students Supplies': 'اللوازم المكتبية والطلابية',
    'Office Equipment': 'معدات المكتب',
    'Other Office Equipment': 'معدات مكتبية أخرى',
    'Other Paints': 'دهانات اخرى',
    Others: 'آحرون',
    'Page Markers & Flags': 'علامات وأعلام الصفحة',
    'Paint & Clay': 'الطلاء والطين',
    PanPastels: 'بان باستيل',
    'Parenting Books': 'كتب الأبوة والأمومة',
    Pastels: 'الباستيل',
    Pencils: 'اقلام رصاص',
    Pens: 'أقلام',
    'Plastic Folders': 'مجلدات بلاستيكية',
    'Plastic Rulers': 'مساطر بلاستيكية',
    'Printing Papers': 'أوراق الطباعة',
    Punchers: 'اللكمات',
    Resin: 'مادة صمغية',
    'Resin Colors': 'ألوان الراتنج',
    'Resin, Adhesives & Cleaners': 'الراتنج والمواد اللاصقة والمنظفات',
    Rulers: 'الحكام',
    'School Handbooks (Gr. 1-12)': 'الكتيبات المدرسية (مجموعة 1-12)',
    'School Packages': 'باكجات مدرسية',
    Scissors: 'مقص',
    'Scissors and Cutters': 'المقصات والقواطع',
    'Silicone Molds': 'قوالب سيليكون',
    Sketchbooks: 'كراسة الرسم',
    'Sketching Pencils': 'رسم أقلام الرصاص',
    'Staplers and Staples': 'كباسات ودبابيس',
    'Steel Rulers': 'الحكام الصلب',
    'Sticky Notes': 'ورق ملاحظات',
    'Stretched Canvas & Panels': 'امتدت قماش وألواح',
    'Student Handbooks': 'كتيبات الطالب',
    'Tapes & Dispensers': 'الأشرطة والموزعات',
    'Tie Dye': 'صبغ التعادل',
    'Transfer Papers': 'أوراق التحويل',
    Uncategorized: 'غير مصنف',
    'Water Bottles': 'زجاجات مياه',
    'Watercolor & Oil Paints': 'الألوان المائية والدهانات الزيتية',
    'Writing Pads': 'دفاتر كتابة',
    Returns_and_Exchange: 'الاسبدال والارجاع',
    bookingTerms: 'شروط الحجز',
    And: 'و',
    I_agree_to_the: 'أنا أوافق على',
    Dont_have_an_account: 'ليس لديك حساب؟',
    Select_Gender: 'حدد نوع الجنس',
    CreatePassword: 'أنشئ كلمة مرور',
    Your_Username: 'اسم المستخدم الخاص بك',
    Male: 'ذكر',
    Female: 'انثى',
    male: 'ذكر',
    female: 'انثى',
    Other: 'آخر',
    other: 'آخر',
    Balance: 'الرصيد',
    'Password cannot be empty': 'لا يمكن أن تكون كلمة المرور فارغة',
    enter_emal_username: 'أدخل عنوان البريد الإلكتروني أو اسم المستخدم',
    Add_to_cart: 'أضف إلى السلة',
    No_Reviews: 'لم يتم تقديم تعليقات',
    Add_Review: 'إضافة مراجعة',
    Hadafy_Deals: 'صفقات هادفي',
    'Hadafy Deals': 'خصومات هدفي',
    'Best Sellers': 'الأفضل مبيعا',
    Best_Sellers_Products: 'أفضل المنتجات مبيعًا',
    Place_Order: 'مكان الامر',
    Agree_terms_Conditions: 'لقد قرأت ووافقت على شروط وأحكام الموقع',
    Your_Personal_data:
      'سيتم استخدام بياناتك الشخصية لمعالجة طلبك ودعمك\n    تجربتك في جميع أنحاء هذا الموقع ، ولأغراض أخرى\n    الموصوفة في منطقتنا',
    Visa_Master_Cards: 'بطاقات الفيزا / الماستر',
    Cash_on_Delivery: 'الدفع عند الاستلام',
    Visa_MasterCard_1_5__fee: 'رسوم فيزا / ماستر كارد 1.5٪',
    My_Orders: 'طلباتي',
    No_Area_Selected: 'لم يتم تحديد منطقة',
    Order_Notes_Detail:
      'ملاحظات حول طلبك ، على سبيل المثال ملاحظات خاصة للتسليم',
    Order_Notes_Optional_: 'ملاحظات الطلب (اختياري)',
    Bill_To_Different_Address: 'فاتورة إلى عنوان مختلف',
    Your_Phone: 'هاتفك',
    Avenue: 'الجادة',
    Block: 'القطعة',
    Your_Area: 'منطقتك',
    Kuwait: 'الكويت',
    Billing_Details: 'تفاصيل الفاتورة',
    Error: 'خطأ',
    Please_select_a_Payment_Method: 'الرجاء اختيار طريقة الدفع',
    View_More: 'عرض المزيد',
    Items: 'أغراض',
    Quantity: 'كمية',
    Your_Country: 'بلدك',
    Your_Postcode: 'رمزك البريدي',
    Postcode: 'رمزك البريدي',
    Your_State: 'ولايتك',
    Your_City: 'مدينتك',
    Address_Line_1: 'العنوان السطر 1',
    Address_Line_2: 'العنوان السطر 2',
    Your_Company: 'شركتك',
    Update_Profile: 'تحديث الملف',
    Enter_New_password: 'أدخل كلمة مرور جديدة',
    Enter_Old_password: 'أدخل كلمة المرور القديمة',
    Your_email_address: 'عنوان بريدك الإلكتروني',
    Your_First_Name: 'اسمك الأول',
    Your_Last_Name: 'اسمك الاخير',
    Sign_Up: 'اشتراك',
    Sign_In: 'تسجيل الدخول',
    Order_Success: 'طلب النجاح',
    Areas: 'المناطق',
    Checkout: 'الدفع',
    Menu: 'قائمة الطعام',
    Categories: 'التصنيفات',
    Register: 'تسجيل',
    All_Products: 'جميع المنتجات',
    Terms_and_Conditions: 'الأحكام والشروط',
    Privacy_Policy: 'سياسة الخصوصية',
    Contact_Us: 'اتصل بنا',
    About_Us: 'معلومات عنا',
    Logout: 'تسجيل الخروج',
    Addresses: 'العناوين',
    Wallet: 'المحفظة',
    Account_Details: 'تفاصيل الحساب',
    Product_Removed_From_Wishlist: 'تمت إزالة المنتج من قائمة الرغبات',
    Removed: 'إزالة',
    Product_Added_to_Wishlist: 'تمت إضافة المنتج إلى قائمة الرغبات',
    SUCCESS: 'نجاح',
    Item_is_already_added_into_cart: 'تمت إضافة العنصر بالفعل إلى سلة التسوق',
    PRODUCT_ADDED_TO_CART: 'تم إضافة المنتج إلى عربة التسوق الخاصة بك بنجاح',
    chooseCar: 'اختر سيارة',
    new: 'جديدة',
    used: 'مستعملة',
    make: 'نوع السيارة',
    model: 'الموديل',
    year: 'سنة الصنع',
    search: 'ابحث',
    selectCar: 'اختر سيارة',
    configure: 'تهيئة',
    payOnline: 'ادفع عبر الإنترنت',
    delivery: 'توصيل',
    featuredCar: 'سيارات مميزة',
    buyNow: 'اشتري الآن',
    finance: 'التمويل',
    vatInc: 'شامل الضريبة المضافة',
    financingAvailable: 'التمويل المتاح',
    butFrmEl_Ektiar: 'لكن من الاقتصادي',
    financingOption: 'خيارات التمويل',
    compitativePrices: 'أسعار منافسة',
    insuranceAvailable: 'التأمين متاح',
    guarenteedPurchase: 'شراء مضمون',
    home: 'الصفحة الرئيسية',
    Home: 'الصفحة الرئيسية',
    financing: 'التمويل',
    close: 'قريب',
    promo: 'الترويجي',
    completeOrder: 'اكمل الطلب',
    callBack: 'معاودة الإتصال',
    selectMake: 'اختر نوع السيارة',
    selectModal: 'اختر الموديل',
    selectYear: 'اختر سنة الصنع',
    color: 'اللون',
    payNow: 'ادفع الآن',
    applyForFinance: 'تقدم بطلب التمويل',
    payFullAmount: 'دفع كامل المبلغ',
    payDeposit: 'دفع مقدم',
    procedToCheckout: 'باشرالخروج من الفندق',
    overView: 'نظرة عامة',
    features: 'المواصفات',
    whyBuyFrmEl_Ektiar: 'لماذا الشراء من الإختيار هو الأفضل',
    customerReview: 'آراء المستهلكين',
    similarVehicles: 'مركبات مماثلة',
    enquireNow: 'استفسر الان',
    brochure: 'كراسة',
    orders: 'لطلب',
    testimonials: 'الشهادات - التوصيات',
    termCondtions: 'شروط وأحكام',
    privacyPolicy: 'سياسة الخصوصية',
    faq: 'الأسئلة الشائعة',
    securePayment: 'دفع امن',
    contactUs: 'اتصل بنا',
    email: 'البريد الإلكتروني',
    telephone: 'رقم الهاتف',
    phone: 'هاتف',
    password: 'كلمه السر',
    confirmPassword: 'تأكيد كلمة المرور',
    login: 'تسجيل الدخول',
    Login: 'تسجيل الدخول',
    forgotPassword: 'نسيت كلمة السر؟',
    signUp: 'سجل',
    showMore: 'أظهر المزيد',
    share: 'شارك',
    aboutUs: 'معلومات عنا',
    addTestimonial: 'أضف شهادة',
    insurance: 'تأمين',
    standard: 'معياري',
    premium: 'قسط التأمين',
    vas: 'خدمة القيمة المضافة',
    shiping: 'الشحن',
    payments: 'المدفوعات',
    roadRecovery: 'خدمة المساندة على الطريق',
    next: 'التالى',
    tinting: 'الصبغ',
    back: 'أسود',
    BackWithIcon: ' < أسود',
    total: 'المجموع',
    vat: 'ضريبة القيمة المضافة',
    vehiclePrice: 'سعر السيارة',
    valeAddService: 'خدمة القيمة المضافة',
    orderNow: 'اطلب الان',
    cart: 'عربة التسوق',
    wishList: 'قائمة الرغبات',
    account: 'الحساب',
    save: 'حفظ',
    myOrders: 'طلباتي',
    orderTotal: 'الطلب الكلي',
    viewOrder: 'مشاهدة الطلب',
    reorder: 'إعادة ترتيب',
    date: 'تاريخ',
    account_information: 'معلومات الحساب',
    firstName: 'الاسم الاول',
    lastName: 'الاسم الأخير',
    change_email: 'تغيير البريد الالكتروني',
    change_password: 'غير كلمة السر',
    confirm_password: 'تأكيد كلمة المرور',
    new_password: 'كلمة سر جديدة',
    current_password: 'كلمة المرور الحالي',
    name: 'اسم',
    preferred_mode_of_contact: 'الوضع المفضل للاتصال',
    mobile: 'التليفون المحمول',
    please_describe_your_enquiry: 'يرجى وصف استفسارك',
    submit_enquiry: 'إرسال الاستفسار',
    login_to_your_account: 'تسجيل الدخول إلى حسابك',
    login_with: 'تسجيل الدخول مع',
    did_not_have_an_account: 'لم يكن لديك حساب',
    order_successfully_placed: 'تم وضع الطلب بنجاح',
    thank_you_for_purchase: 'شكرا للتسوق معنا',
    payment_status: 'حالة السداد',
    my_account: 'حسابي',
    you_can_track_your_order_by_clicking_on: 'يمكنك تتبع طلبك بالضغط على',
    not_ready_to_buy_online_call_us:
      'غير مستعد للشراء عن طريق الانترنت؟ اتصل بنا',
    request_a_call_back: 'طلب استدعاء',
    request_a_quote: 'اطلب تسعيرة',
    free_service_from_el_ekhtiar: 'خدمة مجانية من الاختيار',
    create_your_account: 'أنشئ حسابك',
    already_have_an_account: 'هل لديك حساب',
    my_wishList: 'قائمة رغباتي',
    supporting_documents: 'المستندات',
    salary_certificate: 'شهادة الراتب',
    browse: 'تصفح',
    id_copy: 'نسخة الهوية',
    igama: 'إيغاما',
    driving_license: 'رخصة قيادة',
    cost_certificate: 'شهادة التكلفة',
    your_cart_is_empty: 'عربة التسوق فارغة',
    here_to_help: 'هنا للمساعدة',
    contact_us_by_email: 'اتصل بنا عبر البريد الإلكتروني',
    customer_care: 'العناية بالعملاء',
    contact_us_by_phone: 'اتصل بنا عبر الهاتف',
    my_billing_and_shipping_address_are_the_same:
      'عنوان الفواتير والشحن الخاص بي هو نفسه',
    phone_number: 'رقم الهاتف',
    address: 'عنوان',
    street_address: 'الشارع',
    state: 'المنطقة',
    city: 'المدينة',
    City: 'المدينة',
    avenue:'الجادة',
    house_field:'المنزل/العمارة',
    floor:'الطابق',
    flat:'الشقة',
    country: 'البلد',
    zip_postal_code: 'الرمز البريدي / الرمز البريدي',
    shipping_method: 'طرق الشحن',
    select_showroom: 'حدد صالة العرض',
    about: 'حول',
    yourOrder: 'طلبك',
    specialOffers: 'عروض خاصة',
    profile: 'الملف الشخصي',
    offers: 'عروض',
    locations: 'المواقع',
    availThisOffer: 'استفد من هذا العرض',
    searchNow: 'ابحث الآن',
    selectAll: 'اختر الكل',
    default: 'إفتراضي',
    if_salary_not_credit_to_same_bank: '',
    bank_statement_for_last_3_months: 'إذا لم يتم إضافة الراتب لنفس البنك',
    all_other_mentioned_documents: 'جميع الوثائق الأخرى المذكورة',
    lorem_ipsum_has_been_the_industrys_standard_dummy_text_ever_since_the_1500s:
      'لوريم إيبسوم هو النص الوهمي القياسي في الصناعة منذ القرن الخامس عشر الميلادي ،',
    select: 'تحديد',
    incl: 'بما في ذلك',
    terms_and_conditions: 'البنود و الظروف',
    i_agreed_this_terms: 'وافقت على هذه الشروط',
    payment_methods: 'طرق الدفع',
    payment_method: 'طرق الدفع',
    there_are_no_payment_methods_for_this_address:
      'لا توجد طرق دفع لهذا العنوان',
    you_will_be_redirected_to: 'ستتم إعادة توجيهك إلى',
    al_rajhi_bank: 'مصرف الراجحي',
    portal: 'بوابة',
    your_new_vehicle: 'سيارتك الجديدة',
    included: 'شامل',
    you: 'أنت',
    by_checking_this_you_are_agree_to_the_terms_and_conditions_and_are_entering_into_an_agreement_to_purchase:
      'من خلال التحقق من هذا ، فإنك توافق على الشروط والأحكام وتدخل في اتفاقية الشراء',
    a_car_from_wallan_which_is_legally_binding: 'سيارة ملزمة قانونا من الوعلان',
    there_are_no_shipping_methods_for_this_address:
      'لا توجد طرق شحن لهذا العنوان',
    shipping_address: 'عنوان الشحن',
    chane_address: 'تغيير العنوان',
    new_address: 'عنوان جديد',
    please_enter_your: 'من فضلك أدخل',
    information_saved_successfully: 'تم حفظ المعلومات بنجاح',
    information_and_password_changed_successfully:
      'تم تغيير المعلومات وكلمة المرور بنجاح',
    please_add_valid_information: 'الرجاء إضافة معلومات صحيحة',
    company: 'شركة',
    submit: 'إرسال',
    no_address_found: 'لم يتم العثور على عنوان',
    maintain_your_task_here: 'حافظ على مهمتك هنا',
    task: 'مهمة',
    additional_comments: 'تعليقات اضافية',
    preferred_time_to_call: 'الوقت المفضل للاتصال',
    reason_for_call_back: 'سبب معاودة الاتصال',
    any_additional_omment: 'أي تعليق إضافي',
    news_and_updates: 'الأخبار والتحديثات',
    it_is_a_long_established_fact_that_a_reader_will_be_distracted_by_the_readable_content_of_a_page_when_looking_at_its_layout_The_point_of_using_Lorem_Ipsum_is_that_it_has_a_more_or_less_normal_distribution_of_letters_as_opposed_to_using_Content_here_content_here_making_it_look_like_readable_English:
      'هناك حقيقة مثبتة منذ زمن طويل وهي أن المحتوى المقروء لصفحة ما سيلهي القارئ عن التركيز على الشكل الخارجي للنص أو شكل توضع الفقرات في الصفحة التي يقرأها. الهدف من استخدام لوريم إيبسوم هو أنه يحتوي على توزيع طبيعي -إلى حد ما- للأحرف ، بدلاً من استخدام "هنا يوجد محتوى نصي ، هنا يوجد محتوى نصي" ، مما يجعلها تبدو وكأنها إنجليزية سهلة القراءة',
    yes_subscribeme_to_ElEltiar_NewsLetters:
      'نعم ، اشترك في رسائل البريد الإخبارية',
    title: 'عنوان',
    mr: '.السيد',
    mrs: '.السيدة',
    miss: '.يغيب',
    coming_soon: 'قريبا',
    your_order_is_empty: 'طلبك فارغ',
    an_email_has_been_sent_to_your_account_Please_verify_that_mail:
      'تم إرسال بريد إلكتروني إلى حسابك. يرجى التحقق من هذا البريد',
    this_email_does_not_belong_to_any_account:
      'هذا البريد الإلكتروني لا ينتمي إلى أي حساب',
    please_enter_your_email_address_below_to_receive_a_password_reset_link:
      'يرجى إدخال عنوان بريدك الإلكتروني أدناه لتلقي رابط إعادة تعيين كلمة المرور',
    reset_my_password: 'إعادة تعيين كلمة المرور الخاصة بي',
    order_date: 'تاريخ الطلب',
    item_ordered: 'تم طلب العناصر',
    sku: 'SKU',
    qty: 'كمية',
    price: 'السعر',
    subtotal: 'المجموع الفرعي',
    shiping_and_handling: 'الشحن والمناولة',
    tax_amount: 'قيمة الضريبة',
    grand_total: 'المجموع الكلي',
    order_information: 'معلومات الطلب',
    billing_address: 'عنوان وصول الفواتير',
    your_order: 'طلبك',
    is_Recieved_with: 'تم الاستلام مع',
    full_payment_recevied: 'تم استلام الدفعة الكاملة',
    A_confirmation_Email_and_SMS_has_been_sent_to_contact_details_below:
      'تم إرسال بريد إلكتروني للتأكيد ورسالة نصية قصيرة إلى تفاصيل الاتصال أدناه',
    Share_your_experiance_to_help_others: 'شارك خبرتك لمساعدة الآخرين',
    How_I_can_apply_for_finance: 'كيف يمكنني التقدم للحصول على تمويل؟',
    rate: 'معدل',
    Post_Review: 'مراجعة آخر',
    localizationYou_already_have_a_car_in_your_cart_Would_you_like_to_remove_the_exiting_car_from_the_cart_and_add_this_car:
      'لديك بالفعل سيارة في عربة التسوق الخاصة بك. هل تود إخراج السيارة الخارجة من عربة التسوق وإضافة هذه السيارة؟',
    review: 'إعادة النظر',
    Down_Payment: 'الدفعة المقدمة',
    term: 'الأحكام',
    months: 'الشهور',
    for_more_than_1_car: '(لأكثر من سيارة واحدة)',
    write_a_review: 'أكتب مراجعة',
    email_Address: 'عنوان البريد الالكترونى',
    enter_your_comment: 'أدخل تعليقك',
    i_have_read_and_accept: 'لقد قرأت واستعرض',
    use_as_my_default_billing_address:
      'استخدم كعنوان الفاتورة الافتراضي الخاص بي',
    use_as_my_default_shipping_address:
      'استخدم كعنوان الشحن الافتراضي الخاص بي',
    sort: 'التصنيف حسب',
    filter: 'منقي',
    'Filter By': 'منقي',
    cars: 'سيارة',
    found: 'نتائج البحث ',
    no_record_found: 'لا يوجد سجلات',
    position: 'موضع',
    product_name: 'اسم المنتج',
    apply_filters: 'تطبيق المرشحات',
    password_does_not_match: 'كلمة السر غير متطابقة',
    user_is_successfully_registered: 'تم تسجيل المستخدم بنجاح',
    summary: 'ملخص',
    your_request_has_been_submitted: 'تم تقديم طلبك',
    rating: 'الضرب',
    talk_about_why_you_like_this_review: 'تحدث عن سبب إعجابك بهذا الاستعراض ',
    talk_about_why_you_dislike_this_review:
      'تحدث عن سبب عدم إعجابك بهذه المراجعة',
    add: 'أضف',
    select_show_room: 'حدد صالة العرض',
    user_authentication_failed: 'فشلت مصادقة المستخدم',
    please_login_again: 'الرجاد الدخول على الحساب من جديد',
    please_select: 'الرجاء التحديد',
    show_room: 'صالة عرض',
    engine: 'محرك',
    please_write_details_of_experience: 'يرجى كتابة تفاصيل الخبرة',
    thank_you_for_your_feedback: 'شكرا لك على ملاحظاتك',
    please_select_car_colour: 'الرجاء تحديد لون السيارة',
    share_details_of_your_own_experiance: 'شارك تفاصيل تجربتك الخاصة ',
    you_have_already_selected_a_car: 'لقد اخترت بالفعل سيارة',
    keep_it: 'إحتفظ به',
    remove_existing_car: 'إزالة السيارة الموجودة',
    minimum_deposit_is: 'الحد الأدنى للإيداع هو',
    processing_fee: 'كلفة المعالجة',
    cash_price: 'السعر النقدي',
    down_payment: 'الدفعة الأولى',
    loan_payment: 'قيمة القرض',
    or: 'أو',
    pay_by_credit_cards: 'الدفع بواسطة بطاقة الإئتمان',
    log_out: 'خروج',
    change_language: 'تغيير اللغة',
    multi: 'متعدد',
    personal_information: 'المعلومات الشخصية',
    'Email cannot be empty': 'لا يمكن أن يكون البريد الإلكتروني فارغًا',
    email_is_invalid: 'الرجاء إدخال بريد إلكتروني صالح',
    'Email is Invalid': 'الرجاء إدخال بريد إلكتروني صالح',
    is_removed_from_wishlist: 'is removed from wishlist.',
    is_added_into_wishlist: 'is added into wishlist.',
    mobile_number: 'رقم الجوال',
    what_are_you_looking_for: 'عن ماذا تبحث؟',
    all_orders: 'كل الطلبات',
    fullpayment_rders: 'طلبات الدفع الكاملة',
    split_payments_orders: 'طلبات الدفع المقسم',
    financed_orders: 'طلبات التمويل',
    my_support_tickets: 'تذكرة الدعم الخاصة بي',
    recommendedCars: 'أكثر السيارات شعبية في السوق',
    compare: 'قارن',
    specialPrice: 'انقر لمعرفة السعر الخاص لعملاء الدفع النقدي',
    payInCash: 'الدفع نقدا',
    outstandingPayments: 'المدفوعات المعلقة',
    pay_deposit_note:
      'ملاحظة: افرغ عربة التسوق الخاصة بك قبل سداد جزء، وإلا فسيتم اقتطاع عرض الأسعار',
    note: 'ملاحظة',
    product_details_note:
      'رسوم التأمين الإلزامي للسيارة غير مشمولة في السعر الإجمالي المذكور للسيارة. يمكن للعميل أن يقوم بترتيب التأمين على السيارة المشتراة أو يقوم "الإختيار" أيضاً بالتسهيل للعميل في .شراء التأمين على السيارة برسوم إضافية يقوم بدفعها',
    finance_bank_note:
      'يرجى تقديم اختياراتك للبنك، الدفعة المقدمة، الدفعة النهائية، والتي ستصبح المعلومات المتعلقة في طلب التمويل الخاص بك',
    have_any_queries: 'هل لديك أي استفسار؟ اقرآ ',
    or_call_us: 'أو اتصل بنا',
    rate_and_review: 'اكتب رأيك لخاص',
    contact_date: 'تاريخ الاتصال',
    contact_time: 'أوقات الإتصال',
    number_of_cars_required: 'عدد السيارات المطلوبة',
    brief_overview: 'نظرة عامة موجزة',
    overview_desc:
      'ي حالة طلب عرض أسعار لأكثر من نوع / طراز سيارة، يرجى تقديم التفاصيل هنا',
    phone_number_is_invalid: 'الرجاء إدخال أكثر من 10 رموز أو ما يعادلها',
    extras: 'طلبك',
    select_extras: 'اختر الإضافات',
    extras_desc:
      'حدد الإضافات المطلوبة، الأسعار المعروضة تشمل ضريبة القيمة المضافة',
    registration_charges: 'رسم لوحة الرقم',
    deposit_amount: 'قيمة الضريبة المضافة',
    remaining_amount: 'الكمية المتبقية',
    financed_amount: 'المبلغ الممول',
    monthly_installment: 'القسط الشهري',
    delivery_instruction:
      'يرجى ملاحظة أنه لا يمكن تسليم السيارة إلا للشخص الذي سيتم تسجيل السيارة باسمه',
    map_instruction: ' الرجاء تحديد دبوس الخريطة وفقاً لعنوانك',
    locate_me: 'تحديد موقع لي',
    shipping_policy: 'سياسة الشحن',
    supporting_documnet: 'بيانات الشخص الذي تسجل سيارته باسمه',
    start_condition: 'من بعد التحقق، فقد قرأت وأوافق على',
    end_condition:
      'وأنني أبرم هذه الاتفاقية طوعاً لشراء سيارة من الإختيار وهي ملزمة قانوناً',
    apply_discount_code: 'إدخال رمز الخصم',
    enter_discount_code: 'أدخل رمز الخصم',
    apply: 'تطبيق',
    remove: 'إزالة',
    cart_emty_desc:
      'عربة التسوق فارغة، الرجاء اختيار السيارة التي ترغب بشرائها',
    cart_desc:
      'بحاجة الى مساعدة حول خدماتنا؟ اتصل بنا الآن وسنعاود الاتصال بك قريباً',
    create_ticket: 'إنشاء تذكرة',
    subject: 'الموضوع',
    department: 'القسم',
    last_activity: 'النشاط الاخير',
    view_issue: 'عرض العدد',
    closed: 'مغلق',
    open: 'مفتوح',
    details: 'تفاصيل',
    request_id: 'طلب معرف',
    priority: 'الأولوية',
    status: 'الحالة',
    order: 'طلب',
    message: 'رسالة',
    load_previous_messages: 'تحميل الرسائل السابقة',
    close_ticket: 'إغلاق التذكرة',
    submit_ticket: 'قدم التذكرة',
    history: 'السجّل',
    ticket_close_successfully: 'تم نشر رسالتك بنجاح',
    message_posted_successfully: 'تم إغلاق التذكرة بنجاح',
    please_enter_a_message: 'حقل مطلوب',
    post_a_reply: 'اكتب رداً',
    update: 'تحديث',
    terms_months: 'الشروط / الأشهر',
    loan_amount: 'مبلغ القرض',
    administrative_fee: 'رسوم إدارية',
    finance_cost: 'التكلفة المالية',
    profit_margin_ratio: 'نسبة هامش الربح',
    total_profits: 'إجمالي الأرباح',
    total_insurance: 'إجمالي التأمين',
    total_comprehensive: 'إجمالي شامل',
    total_interest_value: 'إجمالي قيمة الفائدة',
    total_downpayment: 'إجمالي الدفعة المقدمة',
    total_deduction: 'إجمالي الخصم',
    allowed_premium: 'الأعلى. قسط مسموح به',
    ncb: 'البنك الأهلي التجاري‎',
    final_payment: 'الدفعة الأخيرة',
    apply_now: 'قدم الآن',
    enter_location: 'إدخال الدولة',
    coupon_applied_successfully: 'تم تطبيق قسيمتك بنجاح',
    coupon_removed_successfully: 'تمت إزالة قسيمتك بنجاح',
    something_went_wrong: 'هناك خطأ ما! حاول مرة اخرى',
    please_accept_tems: 'الرجاء قبول الشروط والأحكام',
    pleae_select_payment_methods: 'الرجاء تحديد طريقة الدفع',
    sorry_loacation_is_outside_saudi_arabia:
      'عذرا الموقع خارج المملكة العربية السعودية',
    you_are_successfully_logged_in: 'لقد تم تسجيل دخولك بنجاح',
    please_login_to_your_account: 'يرجى تسجيل الدخول إلى حسابك',
    you_are_successfully_logged_out: 'قمت بتسجيل الدخول بنجاح',
    comparison: 'مقارنة',
    tickets: 'مسائل',
    ticket_details: 'تفاصيل التذكرة',
    verify_otp: 'تحقق من كلمة المرور لمرة واحدة',
    your_cart: 'عربتك',
    address_deleted_successfully: 'تم حذف العنوان بنجاح',
    select_an_order: 'حدد طلبًا',
    ticket_posted_successfully: 'تم نشر تذكرتك بنجاح',
    you_have_placed_no: 'لقد وضعت لا',
    please_enter_amount: 'الرجاء إدخال المبلغ',
    request_forwarded: 'تم تحويل طلبك إلى الإدارة المعنية',
    error_type: 'نوع الخطأ',
    report_description: 'وصف تقرير',
    error_description: 'وصف خاطئ',
    send: 'إرسال',
    request_an_extension: 'طلب تمديد',
    you_till_have: 'لديك حتى',
    to_pay_the_remaining_amount: 'لدفع المبلغ المتبقي. طلب تمديد',
    report_an_error: 'الإبلاغ عن خطأ',
    make_your_payment: 'ادفع الآن',
    signin_mob_number: 'رقم الجوال لتسجيل الدخول',
    otp_sent_note:
      'ملاحظة: من فضلك لا تقم بتحديث الصفحة. تم إرسال رسالة نصية قصيرة مع كلمة مرور لمرة واحدة على رقم هاتفك المحمول. يرجى إدخاله في الحقل المخصص',
    enter_otp: 'أدخل كلمة المرور لمرة واحدة',
    continue: 'يكمل',
    send_otp: 'أرسل كلمة المرور لمرة واحدة',
    resend_otp: 'إعادة إرسال كلمة مرور لمرة واحدة',
    verify: 'تحقق',
    verification: 'تحقق',
    'All Products': 'جميع المنتجات',
    'Best Sellers Products': 'الأفضل مبيعا',
    'Office & Student Supplies': 'اللوازم المدرسية والمكتبية',
    'My Account': 'حسابي',
    'Privacy Policy': 'سياسة الخصوصية',
    'Terms & Conditions': 'الأحكام والشروط',
    'Login/Register': 'الدخول / التسجيل',
    'Forgot Password?': 'هل نسيت كلمة المرور؟',
    'Forgot Password': 'هل نسيت كلمة المرور؟',
    'About Us': 'من نحن؟',
    FAQ: 'الأسئلة الشائعة',
    'Returns and Exchange': 'الإسبدال والإرجاع',
    'Contact Us': 'تواصل معنا',
    Hello: 'مرحبا',
    Search: 'بحث',
    'Billing Details': 'عنوان الفاتورة',
    'Shipping Details': 'عنوان الشحن',
    'Ship to Different Address?': 'الشحن الى عنوان اخر؟',
    'Order notes (Optional)': 'ملاحظات؟',
    'First Name': 'الإسم الأول',
    'First name': 'الإسم الأول',
    'Last Name': 'الإسم الأخير',
    'Last name': 'الإسم الأخير',
    'Country: Kuwait': 'الدولة: الكويت',
    Area: 'المنطقة',
    Street: 'الشارع',
    House: 'المنزل',
    'House #': 'المنزل',
    Jaddah: 'جدة‎',
    Email: 'البريد الإلكتروني',
    'Email address': 'عنوان البريد الالكترونى',
    Phone: 'هاتف',
    Shipping: 'الشحن',
    'My Order': 'طلبي',
    Subtotal: 'المجموع',
    Cart: 'عربة التسوق',
    Back: 'عودة',
    item: 'بند',
    items: 'العناصر',
    Item: 'بند',
    Items: 'العناصر',
    Total: 'المجموع الكلي',
    coupon_cannot_be_applied:"عذرا ، هذه القسيمة لا تنطبق على المنتجات المختارة",
    'Same Day Delivery': 'التوصيل في نفس اليوم',
    'Next Day Delivery': 'التسليم في اليوم التالي',
    'No Products Found': 'لا توجود منتجات',
    Orders: 'الطلبات',
    WishList: 'الرغبات',
    'Account Details': 'تفاصيل الحساب',
    'Thank you': 'شكرا',
    'Your order has been received': 'تم اتمام الطلب بنجاح',
    'Balance Remaining': 'الرصيد المتبقي',
    'Amount entered exceeds your wallet balance':
      'المبلغ الذي تم ادخاله يتجاوز رصيد محفظتك',
    Amount: 'المبلغ',
    'Form Incomplete': 'البيانات غير مكتملة',
    'Please fill in': 'الرجاء ادخال',
    'for billing': 'للدفع',
    'for shipping': 'للشحن',
    'Rather not say': 'افضل ان لا اقول',
    'No Code': 'لا يوجد كود',
    'Please enter a valid coupon code': 'الرجاء ادخال كوبون صالح',
    'Invalid Stock': 'مخزون غير صالح',
    'There are only': 'يوجد فقط',
    left: 'left',
    'Out Of Stock': 'انتهى من المخزون',
    'is not in stock right now please check after sometime':
      'لا يوجد في المخزون حاليا الرجاء التأكد في وقت اخر',
    'Form Invalid': 'الفورمه غير صالحة',
    'Please insert email or username':
      'يرجى ادخال البريد الإليكتروني او اسم المستخدم',
    'Reset Password': 'اعادة كلمة المرور',
    'Reset Link Sent to Email':
      'إعادة تعيين الارتباط المرسل إلى البريد الإلكتروني',
    'Please insert password': 'يرجى ادخال كلمة المرور',
    'Passwords are not the same': 'كلمة المرور لا تطابق',
    'Please insert username': 'يرجى ادخال اسم المستخدم',
    'Please insert email': 'يرجى ادخال البريد الإليكتروني',
    Oops: 'عذرا',
    'You must be logged in to add product in wishlist!':
      'يجب ان تدخل لحسابك لإضافة المنتج الى قائمة الرغبات',
    'Subscribe for InStock Notification?':
      'اشترك لإشعار عند وصول المنتج للمخزون',
    'Added to Cart': 'تمت الإضافة الى العربة',
    Subscribe: 'اشتراك',
    Subscribed: 'اشتراك',
    Newness: 'الأجدد',
    Invalid: 'غير صالح',
    'You must be logged in to review a product.':
      'يجب ان تدخل لحسابك  لإضافة تقييم',
    'Minimum Order': 'الحد الأدنى',
    'Minimum order of KD': 'الحد الأدنى هو دينار',
    'is required': 'مطلوب',
    'Please insert Review for the Product': 'يرجى اضافة التقييم للمنتج',
    'Rate Product': 'قيم المنتج',
    'Are you sure you give 1 stars for this product?':
      'هل انت متأكد بتقييم نجمة وحدة لهذا المنتج؟',
    'Limited Quantity': 'كمية محدودة',
    'available right now.': 'متاح حاليا',
    'Update?': 'تحديث؟',
    Update: 'تحديث',
    'is not in stock right now please check after sometime!':
      'لا يوجد في المخزون حاليا الرجاء التأكد في وقت لاحق',
    'Empty Cart': 'العربة فارغة',
    'Would you like to remove all products from the cart?':
      'هل تود ان تحذف كل المنتجات من العربة؟',
    'Delete?': 'الغاء؟',
    'Subscribe for In-Stock Notification?':
      'اشترك لإشعار عند وصول المنتج للمخزون',
    Delete: 'Delete',
    'Delete & Subscribe': 'الغاء واشتراك',
    'Coupon Applied Successfully': 'تم تطبيق الكوبون بنجاح',
    Sorry: 'عذرا',
    'This coupon is not applicable to selected products.':
      'الكوبون لا ينطبق على المنتجات المحدده',
    'Coupon not available': 'الكوبون غير متوفر',
    'Coupon Not Found': 'لم يتم العثور على الكوبون',
    'Please enter valid wallet amount': 'الرجاء ادخال مبلغ محفظة صالح',
    Payment: 'الدفع',
    'Place Order': 'مكان الامر',
    'Cash on Delivery': 'الدفع عند الاستلام',
    'Only Cash on Delivery is supported at the moment.':
      'يتم دعم الدفع عند التسليم فقط في الوقت الحالي',
    'Addresses have been successfully updated': 'تم تحديث العناوين بنجاح',
    'Please fill in first name': 'الرجاء ادخال الإسم الأول',
    'Please fill in last name': 'الرجاء ادخال الإسم الأخير',
    'Please fill in email': 'الرجاء ادخال البريد الإليكتروني',
    'Please fill in display name': 'الرجاء ادخال اسم العرض',
    "Current password can't be empty!":
      'كلمة المرور الحالية لا يمكن ان تكون فارغة',
    "New password can't be empty!": 'كلمة المرور الجديدة لا يمكن ان تكون فارغة',
    "Re-Enter New password can't be empty!":
      'اعادة ادخال كلمة المرور الجديدة لا يمكن ان تكون فارغة',
    'New password and Re-Enter New password not matching!':
      'كلمة المرور الجديدة مع اعادة ادخال كلمة المرور الجديدة غير مطابقة',
    'Account Details have been updated successfully':
      'تم تحديث بيانات الحساب بنجاح',
    'There are only %d %@ left': '%d %@ لم يبقى سوى',
    'Username or Email': 'اسم المستخدم أو البريد الالكتروني',
    Password: 'كلمه السر',
    Username: 'اسم المستخدم',
    'Repeat Password': 'اعد كلمة السر',
    'Date of Birth': 'تاريخ الولادة',
    'Mobile No.': 'رقم الهاتف المحمول',
    Taimaa: 'تيماء',
    Doha: 'الدوحة',
    Sulaibiya: 'الصليبيه',
    Waha: 'الواحة',
    Jahra: 'الجهراء',
    'Saad Al-Abdullah': 'سعد العبدالله',
    Qasr: 'القصر',
    Oyoun: 'العيون',
    Naseem: 'النسيم',
    Naeem: 'النعيم',
    Farwaniya: 'الفروانية',
    Rigai: 'الرقعي',
    Khaitan: 'خيطان',
    'Abdullah Al-Mubarak': 'عبدالله المبارك',
    Andalous: 'الأندلس',
    Firdous: 'الفردوس',
    'Sabah Al-Nasser': 'صباح الناصر',
    Ardiya: 'العارضية',
    Rai: 'الري',
    Ishbilya: 'اشبيلية',
    'Jleeb Al-Shuyoukh': 'جليب الشيوخ',
    Rehab: 'الرحاب',
    Rabia: 'الرابية',
    Omariya: 'العمرية',
    'Al-Dajeej': 'الضجيج',
    'Ali Sabah Al-Salem': 'علي صباح السالم (ام الهيمان)',
    'Sabah Al-Ahmad': 'صباح الأحمد',
    Mangaf: 'المنقف',
    'Khiran Residential': 'خيران السكنية',
    'Mubarak Al-Abdullah': 'مبارك العبدالله (غرب مشرف)',
    Mahboula: 'المهبولة',
    'Jaber Al-Ali': 'جابر العلي',
    Hadiya: 'هدية',
    Fintas: 'الفنطاس',
    Fahaheel: 'الفحيحيل',
    'Fahad Al-Ahmad': 'فهد الأحمد',
    Eqaila: 'العقيلة',
    Assabahiya: 'الصباحية',
    'Al-Riqqa': 'الرقة',
    Dahar: 'الظهر',
    Ahmadi: 'الأحمدي',
    'Abu Halifa': 'ابو حليفه',
    'Sabah Al-Salem': 'صباح السالم',
    Fnaitees: 'الفنيطيس',
    Qurain: 'القرين',
    'Mubarak Al-Kabeer': 'مبارك الكبير',
    Messila: 'المسيلة',
    Qusor: 'القصور',
    'Al-Masayel': 'المسايل',
    Adan: 'العدان',
    'Abu Fatira': 'ابو فطيرة',
    'Abu Al-Hasaniya': 'ابو الحصانية',
    Zahra: 'الزهراء',
    Hateen: 'حطين',
    Salam: 'السلام',
    Shuhada: 'الشهداء',
    Siddeeq: 'الصديق',
    'Maidan Hawalli': 'ميدان حولي',
    Jabriya: 'الجابرية',
    Hawalli: 'حولي',
    Shaab: 'الشعب',
    Salwa: 'سلوى',
    Salmiya: 'السالمية',
    Rumaithiya: 'الرميثية',
    Mishref: 'مشرف',
    Bayan: 'بيان',
    'Al-Bidea': 'البدع',
    Rawda: 'الروضة',
    'North West Al-Sulaibikhat': 'شمال غرب صليبخات',
    Sulaibikhat: 'صليبخات',
    'Jaber Al-Ahmad': 'جابر الأحمد',
    Granada: 'غرناطة',
    Qairawan: 'القيروان',
    Nahdha: 'النهضة',
    'Bneid Al-Gar': 'بنيد القار',
    Khaldiya: 'الخالدية',
    Surra: 'السرة',
    Yarmouk: 'اليرموك',
    'Shuwaikh Residential': 'شويخ السكنية',
    Qortuba: 'قرطبة',
    Adailiya: 'العديلية',
    Kaifan: 'كيفان',
    Faiha: 'الفيحاء',
    Shamiya: 'الشامية',
    Qibla: 'قبلة',
    Qadsiya: 'القادسية',
    Nuzha: 'النزهة',
    Sharq: 'شرق',
    Dasma: 'الدسمة',
    Daiya: 'الدعية',
    'Kuwait City': 'مدينة الكويت',
    Mansouriya: 'المنصورية',
    'Abdullah Al-Salem': 'عبدالله السالم',
    'Registering with Hadafy you agree to our': 'التسجيل مع هدفي أنت توافق على',
    and: 'و',
  },
});
