import { Dimensions, I18nManager, StyleSheet,Platform } from 'react-native';

export const COLORS = {
  primary: '#17436F',
  secondary: `#EE699D`,
  dark: '#2A2A2A',
  light: `#F3F3F3`,
  placeholder: `#818181`,
  lightGray: `#EEEEEE`,
  gray: '#F1F1F1',
  green: '#43E97B',
  success: '#008000',
  purple: '#542ea6',
  warning: '#f59e0b',
  teal: '#0f766e',
  headingDark: '#434343',
  separator: `#DDDDDD`,
  welcomeHeading: `#707070`,
  loginInput: `#A6A6A6`,
  loginInputBorder: `#DADADA`,
  loginSecureText: `#C6CBD4`,
  google: '#DD4B39',
  facebook: `#3B5998`,
  shortDescription: '#656565',
  filterSeparator: 'rgba(161,161,161,0.13)',
  secondaryLowOpacity: `rgba(238, 105, 157, 0.3)`,
  status: {
    Pending: `#EE699D`,
    Processing: '#EEE169',
    'On-Hold': '#17436F',
    Complete: '#53CE57',
    Canceled: '#707070',
    Refunded: '#0f766e',
    Failed: '#DC3545',
    Voided: '#656565',
  },
};

const carouselImageContainerWidth = Dimensions.get('screen').width * 0.95;
const carouselImageContainerHeight = 175;
const carouselImageWidth = carouselImageContainerWidth * 0.7;

export const SCREEN_WIDTH = Dimensions.get('screen').width;
export const SCREEN_HEIGHT = Dimensions.get('screen').height;
const PRODUCT_CARD_WIDTH = SCREEN_WIDTH * 0.45;
const PRODUCT_CARD_HEIGHT = PRODUCT_CARD_WIDTH * (84 / 55);

export const styles = StyleSheet.create({
  compareText: { fontSize: 18, marginLeft: 5, textAlign: 'left' },
  compareView: {
    width: '100%',
    position: 'absolute',
    bottom: 0,
    zIndex: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    paddingVertical: 10,
    paddingHorizontal: 5,
    
  },
  languageScreenContainer: {
    height: '100%',
    backgroundColor: 'white',
    paddingHorizontal: 10,
  },
  languageItemContainer: {
    marginVertical: 10,
    borderBottomWidth: 1,
    borderColor: COLORS.separator,
    paddingVertical: 10,
    paddingHorizontal: 5,
  },
  areaZoneContainer: {
    padding: 10,
    marginRight: 5,
    borderRadius: 25,
    borderColor: COLORS.secondary,
    borderWidth: 1,
  },
  areaContainer: {
    flex: 1,
    backgroundColor: '#fff',
    paddingHorizontal: 15,
    width: '100%',
  },
  filterScreenContainer: {
    backgroundColor: 'white',
    paddingHorizontal: 20,
    flex: 1,
  },
  filterSliderText: {
    borderColor: COLORS.secondary,
    borderWidth: 1,
    borderRadius: 3,
    padding: 5,
    textAlign: 'center',
    color: COLORS.secondary,
    width: '23%',
    fontSize: 12,
  },
  filterSliderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  waitlistBtnContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  waitlistTextInput: {
    width: '94%',
    // height: 50,
    marginBottom: 10,
    backgroundColor: '#fff',
    borderRadius: 15,
    paddingHorizontal: 10,
    height: 40
  },
  waitlistSubHeaderText: { marginBottom: 10, textAlign: 'left', paddingLeft: 1 },
  waitlistHeaderText: {
    marginBottom: 10,
    textAlign: 'center',
    color: 'black',
    fontWeight: 'bold',
    fontSize: 18,
  },
  waitlistHeader: {
    backgroundColor: '#e1e1e1',
    width: '90%',
    paddingVertical: 20,
    borderRadius: 15,
    alignItems: 'center',
  },
  waitListModalContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  isLoadingMoreIndicator: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  activityIndicator: {
    width: 50,
    height: 50,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  compareBtn: { width: '100%', margin: 0 },
  compareName: {
    fontSize: 18,
    textAlign: 'left',
    color: '#000',
    marginBottom: 5,
  },
  comparePrice: {
    marginVertical: 5,
    fontSize: 18,
    textAlign: 'left',
    color: COLORS.primary,
  },
  compareImage: { height: 225, width: '100%', borderRadius: 3 },
  compareCard: {
    flex: 1,
    paddingHorizontal: 10,
    backgroundColor: '#fff',
  },
  compareCardContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  compareTextRight: {
    flex: 1,
    paddingLeft: 10,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderColor: COLORS.separator,
    paddingVertical: 15,
    fontSize: 18,
    color: '#000',
    textAlign: 'justify',
  },
  compareTextLeft: {
    flex: 1,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: COLORS.separator,
    paddingVertical: 15,
    fontSize: 18,
    color: '#000',
    textAlign: 'justify',
    paddingRight: 10,
  },
  compareHeading: {
    fontSize: 24,
    textAlign: 'left',
    color: '#000',
    fontWeight: 'bold',
    marginLeft: 10,
    marginVertical: 15,
  },
  compareTextContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 10,
  },
  orderDetailPaymentName: {
    flexGrow: 1,
    fontSize: 18,
    textAlign: 'left',
    color: '#000',
  },
  cartItemQuantityText: {
    padding: 10,
    fontSize: 16,
    textAlign: 'left',
    color: '#000',
  },
  cartItemQuantityContainer: {
    flexDirection: 'row',
    width: '50%',
    justifyContent: 'space-between',
    backgroundColor: '#F6F6F6',
    marginLeft: 15,
    height: 40,
    alignItems: 'center',
    paddingHorizontal: 15,
    borderRadius: 5,
  },
  cartItemPriceText: {
    fontSize: 16,
    textAlign: 'left',
    color: '#000',
    fontWeight: '600',
    color: COLORS.primary,
    marginLeft: 15,
  },
  cartItemNameText: {
    fontSize: 16,
    textAlign: 'left',
    color: '#000',
    fontWeight: '400',
    marginLeft: 15,
    width: '80%',
  },
  cartItemTextContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cartItemContainer: {
    flexDirection: 'row',
    width: '100%',
    height: 150,
    marginVertical: 10,
    backgroundColor: '#fff',
    // shadowColor: '#a3a3a3',
    // shadowOffset: {
    //   width: 4,
    //   height: 4,
    // },
    // shadowOpacity: 0.32,
    // shadowRadius: 3,

    // elevation: 5,
    borderRadius: 5,
    borderColor: 'rgb(230,230,230)',
    borderWidth: 1,
  },
  orderDetailCardPriceText: {
    fontSize: 18,
    textAlign: 'left',
    color: '#000',

    fontWeight: '700',
    color: COLORS.primary,
  },
  orderDetailCardSmallText: {
    fontSize: 14,
    textAlign: 'left',
    color: COLORS.placeholder,
  },
  orderDetailCardTextContainer: { flex: 2, paddingVertical: 15, paddingLeft: 15 },
  orderDetailCardContainer: {
    flexDirection: 'row',
    width: '100%',
    height: 140,
    marginVertical: 10,
    backgroundColor: '#fff',
    shadowColor: '#a3a3a3',
    shadowOffset: {
      width: 4,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 3,

    elevation: 5,
    borderRadius: 5,
  },
  orderCardPrice: {
    fontSize: 16,
    textAlign: 'left',
    color: '#000',
    marginVertical: 2,
    fontWeight: 'bold',
  },
  orderCardStatus: {
    paddingVertical: 2,
    paddingHorizontal: 5,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
    alignSelf: 'flex-start',
  },
  orderCardDate: {
    fontSize: 14,
    textAlign: 'left',
    color: COLORS.shortDescription,
    marginTop: 2,
  },
  oderCardContainer: {
    marginBottom: 10,
    backgroundColor: '#F9F9F9',
    paddingBottom: 10,
    paddingTop: 5,
    paddingHorizontal: 2,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  paymentPolicy: {
    textAlign: 'justify',
    color: COLORS.shortDescription,
    fontWeight: 'bold',
  },
  paymentShortDesc: {
    textAlign: 'justify',
    color: COLORS.shortDescription,
    marginVertical: 15,
  },
  paymentName: {
    flexGrow: 1,
    marginLeft: 10,
    fontSize: 16,
    textAlign: 'left',
    color: '#000',
  },
  paymentCard: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
  },
  paymentCardContainer: {
    width: '100%',
    paddingHorizontal: 5,
    paddingVertical: 3,
    backgroundColor: COLORS.filterSeparator,
  paddingVertical:8,
    // shadowColor: '#a3a3a3',
    // shadowOffset: {
    //   width: 4,
    //   height: 4,
    // },
    // shadowOpacity: 0.32,
    // shadowRadius: 3,
    // elevation: 5,
    borderRadius: 3,
    marginVertical: 10,
  },
  checkoutOrderNotesInput: {
    borderColor: COLORS.loginInputBorder,
    borderWidth: 1,
    flexGrow: 1,
    height:100,
    paddingLeft:10,
    paddingVertical:0,
    paddingTop:5

  },
  checkoutOrderNotes: {
    width: '100%',
    marginVertical: 15,
  },
  checkoutHiddenView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  checkoutSubHeading: {
    fontWeight: '700',
    fontSize: 18,
    textAlign: 'left',
    color: '#000',

    marginBottom: 10,
  },
  checkoutHeading: {
    fontSize: 30,
    textAlign: 'left',
    color: '#000',
    marginBottom: 20,
  },
  checkoutScrollView: {
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  confirmBtn: { width: '85%', marginVertical: 20 },
  confirmThanksLong: {
    fontSize: 14,
    textAlign: 'left',
    color: '#000',

    marginVertical: 10,
    textAlign: 'center',
    width: '70%',
  },
  confirmOrderId: {
    fontSize: 14,
    textAlign: 'left',
    fontWeight: '600',
    color: COLORS.secondary,
    marginTop:10
  },
  confirmThanks: {
    fontSize: 18,
    textAlign: 'left',
    color: COLORS.shortDescription,
    marginBottom: 5,
  },
  confirmHeading: {
    fontSize: 30,
    textAlign: 'left',
    color: '#000',
    marginVertical: 10,
  },
  confirmContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  addressInput: {
    width: '100%',
    borderBottomColor: COLORS.loginInputBorder,
    borderBottomWidth: 1,
    marginBottom: 20,
  },
  cartCodeBtn: { width: '30%', height: '100%', margin: 0 },
  cartTextInp: {
    width: '70%',
    height: '100%',
    backgroundColor: COLORS.gray,
    paddingHorizontal: 10,
    textAlign: I18nManager.isRTL ? 'right' : 'left',
    color: COLORS.dark
  },
  cartCodeView: {
    flexDirection: 'row',
    height: 55,
    marginTop: 10,
    borderRadius: 3,
    marginBottom: 20,
    width: '100%',
  },
  cartProductView: {
    width: '100%',
    flexWrap: 'wrap',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cartAdditionalInfoText: {
    color: COLORS.dark,
    fontSize: 14,
    textAlign: 'left',
    color: '#000',
  },
  cartScrollView: {
    paddingHorizontal: 10,
    paddingTop: 10,
    backgroundColor: '#fff',

  },
  cartHeader: {
    fontSize: 30,
    textAlign: 'left',
    color: '#000',
    marginBottom: 5,
  },
  detailReviewDate: { marginVertical: 10, textAlign: 'justify' },
  detailReview: { marginVertical: 10, textAlign: 'justify' },
  detailReviewRating: {
    color: 'white',
    fontSize: 18,
    textAlign: 'left',
    color: '#000',
  },
  detailReviewRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    backgroundColor: COLORS.secondary,
    width: 60,
    height: 25,
    borderRadius: 5,
    marginVertical: 10,
    marginLeft: 10,
  },
  detailReviewContainer2: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
  },
  detailReviewHeading2: {
    color: COLORS.secondary,
    fontSize: 18,
    textAlign: 'left',
  },
  detailReviewHeading: {
    fontSize: 18,
    textAlign: 'left',
    color: '#000',
    fontWeight: '600',
    marginRight: 10
  },
  detailReviewContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical:10
  },
  detailReviewSubContainer: {
    flexDirection: 'row',
    alignItems: 'center'
  },
  detailAdditionalInfoText2: {
    color: COLORS.dark,
    fontSize: 14,
    textAlign: 'left',
  },
  detailAdditionalInfoText: {
    color: COLORS.secondary,
    fontSize: 14,
    textAlign: 'left',
  },
  detailAdditionalInfoView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  detailShortDescText: {
    textAlign: 'justify',
    color: COLORS.shortDescription,
    paddingLeft:25
  },
  detailQuantityText: {
    fontSize: 20,
    color: '#000',
  },
  detailQuantityBtn: {
    width: '20%',
    height: 40,
    flexDirection:'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: COLORS.lightGray,
    borderRadius: 3,
    borderWidth:1,
    borderColor: COLORS.lightGray,
  },
  detailQuantityContainer: {
    flexDirection: 'row',
    marginBottom: 15,
    alignItems: 'center',
  },
  detailInfoHeading: {
    marginTop: 18,
    fontWeight: '700',
    fontSize: 18,
    textAlign: 'left',
    color: '#000',

    marginBottom: 10,
  },
  detailFont18Secondary: {
    fontSize: 18,
    textAlign: 'left',
    color: COLORS.secondary,
  },
  detailFont14White: {
    color: 'white',
    fontSize: 14,
    textAlign: 'left',
  },
  detailRatingView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    backgroundColor: COLORS.secondary,
    width: 50,
    height: 25,
    borderRadius: 2,
    // marginVertical: 10,
  },
  detailCenterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailPrice: {
    fontSize: 20,
    textAlign: 'left',
    fontWeight: '500',
    color: COLORS.primary,
  },
  detailRegularPrice: {
    fontSize: 16,
    textAlign: 'left',
    color: COLORS.placeholder,
    textDecorationLine: 'line-through',
  },
  detailPriceView: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  detailName: { fontSize: 20, textAlign: 'left', color: '#000', marginTop: 15 },
  detailColorCard: {
    width: 50,
    height: 50,
    borderRadius: 3,
    marginRight: 5,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#a3a3a3',
    shadowOffset: {
      width: 4,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 3,

    elevation: 5,
  },
  detailSizeCard: {
    width: 50,
    height: 50,
    borderRadius: 3,
    marginRight: 5,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#a3a3a3',
    shadowOffset: {
      width: 4,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 3,

    elevation: 5,
  },
  searchCardPrice: {
    fontSize: 16,
    textAlign: 'left',
    fontWeight: '600',
    color: COLORS.primary,
    marginLeft: 15,
  },
  searchCardText: {
    fontSize: 16,
    textAlign: 'left',
    fontWeight: '400',
    marginLeft: 15,
  },
  searchCardContainer: {
    flexDirection: 'row',
    width: '100%',
    height: 140,
    marginVertical: 10,
    backgroundColor: '#fff',
    borderRadius: 5,
    borderColor: 'rgb(230,230,230)',
    borderWidth: 1,
    // shadowColor: '#a3a3a3',
    // shadowOffset: {
    //   width: 4,
    //   height: 4,
    // },
    // shadowOpacity: 0.32,
    // shadowRadius: 3,

    // elevation: 5,
  },
  searchCard: {
    flexDirection: 'row',
    width: '100%',
    height: 140,
    marginVertical: 10,
    backgroundColor: '#fff',
    shadowColor: '#a3a3a3',
    shadowOffset: {
      width: 4,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 3,

    elevation: 5,
    borderRadius: 5,
  },
  cartItemQtyBtnView: {
    flexDirection: 'row',
    width: '50%',
    justifyContent: 'space-between',
    backgroundColor: '#F6F6F6',
    marginLeft: 15,
    height: 40,
    alignItems: 'center',
    paddingHorizontal: 15,
    borderRadius: 5,
  },
  cartItemBtnText: {
    padding: 10,
    fontSize: 16,
    textAlign: 'left',
  },
  searchCardImageView: {
    flex: 1,
    paddingVertical: 5
  },
  searchCardImage: {
    width: '100%',
    height: '100%',
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,

  },
  searchCardTextView: {
    flex: 2,
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  searchCardBtn: {
    height: 40,
    width: '50%',
    backgroundColor: COLORS.primary,
    alignSelf: 'flex-end',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 4,
    marginRight: 15,
  },
  primaryBtnText12: {
    color: '#fff',
    fontSize: 12,
    textAlign: 'left',
  },
  primaryBtnText14: {
    color: '#fff',
    fontSize: 14,
    textAlign: 'left',
  },
  primaryBtnText16: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'left',
  },
  filterItemText: { fontSize: 18, textAlign: 'left', color: '#000' },
  filterItemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    alignItems: 'center',
    height: 50,
  },
  filterText: {
    color: COLORS.primary,
    fontSize: 20,
    textAlign: 'left',
    marginTop: 15,
    marginBottom:10
  },
  filterHeading: {
    fontSize: 30,
    textAlign: 'left',
    color: '#000',
    marginVertical: 10,
  },
  filterClose: {
    backgroundColor: 'rgba(255,255,255,0.6)',
    width: '100%',
    flexGrow: 1,
    justifyContent: 'flex-end',
  },
  allProductHeader: {
    fontSize: 30,
    textAlign: 'left',
    color: '#000',
    marginTop: 10,
    marginLeft: 10,
  },
  allProductScrollView: {
    backgroundColor: '#fff',
    paddingBottom: 20,
    flex: 1,
  },
  productDetailScrollView: {
    backgroundColor: 'white',
    paddingHorizontal: 10,
    // paddingBottom: 20,
    flex: 1,
  },
  loginInfoText: { color: COLORS.loginInput },
  loginInfo: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  forgetInfo: {
    width: '100%',
    alignItems: 'flex-end',
    justifyContent: 'center',
    marginVertical: 10,
  },
  loginTextInput: {
    flexGrow: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  textInput: {
    paddingVertical: 0,
    flexGrow: 1,
    textAlign: I18nManager.isRTL ? 'right' : 'left',
    color: '#000',
    marginBottom:5,
    // height:30,
    

  },
  loginInputHeading: {
    fontSize: 14,
    textAlign: 'left',
    color: COLORS.loginInput,
    marginBottom:5
  },
  loginInput: {
    width: '100%',
    borderBottomColor: COLORS.loginInputBorder,
    borderBottomWidth: 1,
    marginBottom: 20,
  },
  loginHeader: {
    fontSize: 30,
    textAlign: 'left',
    color: '#000',
    marginBottom: 35,
  },
  ph20: { paddingHorizontal: 20 },
  ph10: { paddingHorizontal: 10 },
  pv10: { paddingVertical: 10 },
  ph15: { paddingHorizontal: 15 },
  pv15: { paddingVertical: 15 },
  flex1: { flex: 1 },
  keyboardAvoidingViewStyle: { flex: 1, backgroundColor: 'white' },
  welcomeButtonsContainer: { flex: 1, width: '100%', justifyContent: 'center' },
  welcomeImageContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  welcomeSubHeading: {
    fontSize: 18,
    textAlign: 'left',
    color: COLORS.welcomeHeading,
  },
  welcomeHeadingBold: { fontWeight: 'bold', color: COLORS.welcomeHeading },
  welcomeHeading: {
    fontSize: 20,
    textAlign: 'left',
    color: COLORS.welcomeHeading,
  },
  welcomeHeadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  welcomeContainer: {
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    height: '100%',
  },
  centerContainer: {
    width: '100%',
    height: SCREEN_HEIGHT * 0.8,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  drawerListHeaderText: {
    color: COLORS.primary,
    fontSize: 18,
    textAlign: 'left',
  },
  drawerListHeaderContainer: {
    width: '100%',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 15,
  },
  drawerListItemSVG: {
    // backgroundColor: COLORS.secondary,
    width: 40,
    height: 40,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  drawerListItemSVGContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flexGrow: 1,
  },
  drawerListItemContainer: {
    flexDirection: 'row',
    width: '100%',
    marginVertical: 10,
    paddingHorizontal: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  separator: {
    width: '95%',
    borderTopWidth: 1,
    borderColor: COLORS.separator,
    alignSelf: 'center',
  },
  drawerSeparator: { width: '95%', marginVertical: 15, alignSelf: 'center' },
  drawerProfileInfoContainer: { justifyContent: 'center', paddingLeft: 10 },
  drawerProfileImage: { width: 50, height: 50, borderRadius: 50 },
  drawerProfileContainer: {
    flexDirection: 'row',
    width: '100%',
    marginTop: '7%',
    marginBottom: 10,
    paddingHorizontal: 10,
  },
  popularImage: {
    width: '100%',
    height: Dimensions.get('screen').width * 0.47 * (180 / 157),
    borderRadius: 5,
  },
  popularView: { width: '47%', borderRadius: 5, marginTop: 20 },
  popularProductView: {
    width: '100%',
    flexWrap: 'wrap',
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  searchProductView: {
    width: '95%',
    flexWrap: 'wrap',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop:20
  },
  productCardSVG: {
    alignItems: 'center',
    justifyContent: 'center',
    margin: 3,
  },
  flexRowCenter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flexRowHeight: {
    flexDirection: 'row',
    alignItems: 'center',
    height: '100%',
  },
  productCardShoppingBag: {
    padding: 3,
    width: 30,
    height: 30,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.primary,
  },
  productCardName: { fontSize: 14, width: '80%', textAlign: 'left', color: 'black' },
  productCardInfoViewContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 5,
    width: '100%',
  },
  productCardRating: {
    marginLeft: 3,
    fontSize: 11,
    textAlign: 'left',
    color: COLORS.secondary,
  },
  productCardPrice: {
    fontSize: 16,
    textAlign: 'left',
    color: COLORS.primary,
  },
  productCardInfoView: { 
    paddingHorizontal: 5, 
    marginTop: 5 
  },
  productCardImage: {
    width: '100%',
    height: PRODUCT_CARD_WIDTH,
    borderRadius: 5,
  },
  productCardStock: {
    width: '100%',
    height: PRODUCT_CARD_WIDTH*1.5,
    borderRadius: 5,
  },
  productCardImageView: { 
    width: '100%', 
    marginTop: 5 
  },
  productCardSVGView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    width: '100%',
    zIndex: 2,
    alignSelf: 'center',
    paddingHorizontal: 5,
    top: 5

  },
  productCardView: {
    width: PRODUCT_CARD_WIDTH,
    minHeight: PRODUCT_CARD_HEIGHT,
    // marginHorizontal: 10,
    marginTop: 20,
    backgroundColor: 'white',
    borderRadius: 5,
    borderColor: 'rgb(230,230,230)',
    borderWidth: 1,
    paddingVertical: 7
  },
  homeListProductCardView: {
    width: PRODUCT_CARD_WIDTH + 20,
    minHeight: PRODUCT_CARD_HEIGHT,
    marginRight: 15,
    // marginHorizontal: 10,
    // marginTop: 20,
    backgroundColor: 'white',
    borderRadius: 5,
    borderColor: 'rgb(230,230,230)',
    borderWidth: 1,
    paddingVertical: 7
  },
  carouselButtonText: {
    textAlign: 'center',
    color: 'white',
    fontSize: 10,
    fontWeight: '400',
  },
  carouselButton: {
    padding: 5,
    backgroundColor: COLORS.primary,
    width: 70,
    height: 22,
    borderRadius: 2,
    justifyContent: 'center',
    alignItems: 'center',
  },
  carouselDescription: {
    fontWeight: '400',
    fontSize: 16,
    textAlign: 'left',
    color: COLORS.headingDark,
  },
  carouselprimary: {
    color: COLORS.primary,
    fontWeight: '100',
    fontSize: 10,
    textAlign: 'left',
  },
  carouselTextView: {
    position: 'absolute',
    width: '100%',
    paddingLeft: '10%',
    zIndex: 2,
    justifyContent: 'space-evenly',
    height: carouselImageContainerHeight,
  },
  carouselImage: {
    width: carouselImageWidth,
    height: carouselImageContainerHeight,
  },
  carousel: {
    backgroundColor: COLORS.lightGray,
    width: '95%',
    marginTop: 20,
  },
  carouselImageComponentView: {
    width: '95%',
    height: carouselImageContainerHeight,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  categoryCardImage: {
    width: '100%',
    height: '100%',
    borderRadius: 5,
  },
  categoryCardContainer: {
    width: 114,
    height: 65,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 10,
    marginTop: 10,
    borderRadius: 5,
  },
  categoryCardTextContainer: {
    position: 'absolute',
    width: 114,
    height: 65,
    zIndex: 2,
    backgroundColor: 'rgba(23, 67, 111, 0.75)',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryCardText: {
    fontWeight: '700',
    color: 'white',
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  shadowView: {
    shadowColor: '#a3a3a3',
    shadowOffset: {
      width: 4,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 3,

    elevation: 5,
  },
  sectionHeaderOnPressText: {
    fontWeight: '100',
    fontSize: 14,
    textAlign: 'left',
    color: '#434343',
  },
  sectionHeaderHeading: {
    fontWeight: '500',
    fontSize: 22,
    textAlign: 'left',
    color: 'black',
  },
  sectionHeaderContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '95%',
    marginTop: 20,
    alignItems: 'center',
  },
  searchBarText: {
    fontSize: 18,
    color: '#000',
    textAlign: I18nManager.isRTL ? 'right' : 'left',
    width:'100%',
    height:'100%'

  },
  homeScrollView: {
    alignItems: 'center',
    paddingBottom: 10,
    backgroundColor: '#fff',
  },
  homeBannersContainer: {  flexDirection: 'row', justifyContent: 'space-between', height: 175, marginVertical: 10},
  homeBannerView: { 
    width: '49%', 
    height: '100%',
    paddingVertical: 10
  },
  homeBannerImage: { 
    width: '100%', 
    height: '100%',
    // resizeMode: 'contain'
  },



  homeSearchBar: {
    alignSelf: 'center',
    width: '95%',
    height: 52,
    backgroundColor: 'white',
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
    borderRadius: 8,
    borderWidth:1,
    borderColor:'#ccc'
    // shadowColor: '#a3a3a3',
    // shadowOffset: {
    //   width: 4,
    //   height: 4,
    // },
    // shadowOpacity: 0.32,
    // shadowRadius: 3,

    // elevation: 5,
  },
  homeHeader: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  marginLeft10: { marginLeft: 10 },
  smallBtnContainer: {
    width: 76,
    height: 24,
    borderRadius: 16,
    borderColor: COLORS.dark,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: 2,
  },
  headerTitleBtnContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  whatsappIcon: {
    width: 70,
    height: 70,
    backgroundColor: '#40C351',
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    bottom: 30,
    left: 20,
    zIndex: 999
  },
  productsTableView :{
    borderWidth: 1, width: '90%'
  },
  productRowView:{
    borderBottomWidth: 1, width: '100%', paddingHorizontal: 10, flexDirection: 'row'
  },
  productNameColumn:{
    width: '60%', paddingVertical: 10
  },
  qtyColumn:{
     borderLeftWidth: 1, paddingVertical: 10, alignItems: 'center', width: '15%' 
  },
  totalsColumn:{
    borderLeftWidth: 1, paddingVertical: 10, alignItems: 'center', width: '25%' 
  }
});

export const CARD_TEXT_OPACITY = 0.5;
export const CARD_COLORS = [
  { backgroundColor: `rgba(23, 67, 111, ${CARD_TEXT_OPACITY})` },
  { backgroundColor: `rgba(238, 105, 157, ${CARD_TEXT_OPACITY})` },
];
